chore: (#8) CI/CD 세팅을 위해 yml 파일을 생성한다.
KUSITMS-30th-TEAM-C/backend pull request #10
Opened 2024-10-10 04:07 UTC by HoyeongJeon

## ✅ PR 유형
어떤 변경 사항이 있었나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

---

## 📝 작업 내용
이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

- .github 폴더 안에 workflows 폴더 생성
- ci, cd를 위한 yml 파일 생성

---

## ✏️ 관련 이슈
본인이 작업한 내용이 어떤 Issue Number와 관련이 있는지만 작성해주세요

ex)
- Related to : #8 

---

## 🎸 기타 사항 or 추가 코멘트

2024-10-13 18:26 UTC, anxi01 requested changes
스크립트 관련 내용에 대한 리뷰는 아닙니다!
현재 작업본이 예전부터 진행중이었던 거라 예전에 제 커밋들이랑 혼합되어 있어요!
많이 섞여있는 건 아니지만 나중에 작업이 더 커지고 겹쳐지면 커밋이 더 많이 혼합될 수 있습니다!

이걸 해결하는 가장 쉬운 방법이 현재 작업 브랜치와 dev 브랜치를 리베이스해서 최신화를 계속 해주시면 쉽게 해결되실 거 같습니다!

지금 제 커밋들이 여러개 있는데 
`git rebase -i HEAD~{해당 PR 시작 지점}`
이렇게 해서 제 커밋들은 삭제하시고 `git push -f` 해서 올려주세요!

아니면 
![스크린샷 2024-10-14 오전 3 23 37](https://github.com/user-attachments/assets/51033dac-393d-4fa7-8525-93a532607387)
![스크린샷 2024-10-14 오전 3 23 56](https://github.com/user-attachments/assets/83b6d3dd-6c73-4d81-b632-ec4dbe243a2b)
![스크린샷 2024-10-14 오전 3 24 18](https://github.com/user-attachments/assets/d249f49c-c46a-4d34-8d27-03c47ee65ecf)

아니면 GUI 이용해서 형의 PR 첫 작업을 우클릭해서 `여기부터 대화식으로 리베이스` 
하신 후에 사진과 같이 제 커밋들은 전부 삭제하고 `git push` 하면 형이 작업한 커밋만 남을 거에요!!

해당 작업본에 대한 리뷰는 오늘 중으로 달겠습니다!
고생하셨습니다!!

2024-10-13 18:26 UTC, anxi01 commented
GUI 방식인 두번째 방식으로 해보시는걸 추천합니다! 
다음 회의 때 첫번째 방식은 알려드릴게요!!!

2024-10-14 02:14 UTC, HoyeongJeon commented
> GUI 방식인 두번째 방식으로 해보시는걸 추천합니다!
> 다음 회의 때 첫번째 방식은 알려드릴게요!!!
와 이런거 몰랐는데 감사합니다~~~~!!!! 
다시 수정했어요~!

2024-10-14 05:09 UTC, anxi01 approved these changes
고생하셨습니다!
인프라의 신 갓호영😎

2024-10-14 06:30 UTC, merged