refactor: (#150) MemberID 생성시 Sequential UUID를 사용하도록 변경한다.
KUSITMS-30th-TEAM-C/backend pull request #152
Opened 2024-11-26 13:57 UTC by HoyeongJeon

## ✅ PR 유형
어떤 변경 사항이 있었나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

---

## 📝 작업 내용

- MemberID 생성시 Sequential UUID를 사용하도록 변경한다.

![image](https://github.com/user-attachments/assets/3cf1d860-f11b-4d55-b846-3d173f1b35ea)

---

## ✏️ 관련 이슈

- Resolves : #150 

---

## 🎸 기타 사항 or 추가 코멘트
UUID 전략을 설정했을 때 아닐 때 테스트를 거쳤습니다.

참고
https://docs.jboss.org/hibernate/orm/6.6/userguide/html_single/Hibernate_User_Guide.html#identifiers-generators-IdGeneratorType

2024-11-26 17:16 UTC, anxi01 requested changes
고생하셨습니다!
Sequential UUID를 이렇게도 하는군요..! 
많이 배우고 갑니당

2024-11-26 17:16 UTC, anxi01 commented on src/main/java/spring/backend/core/infrastructure/persistence/interceptor/SequentialUUID.java
> +public @interface SequentialUUID {
인터셉터와는 관련이 없습니다!
SequentialUUIDGenerator의 ID 생성 방식을 지정하는 어노테이션이니 SequentialUUIDGenerator와 같은 위치에 존재하면 좋을 거 같아요! (아님 공유하며 사용하니 persistence/shared 하위에 존재해도 좋을 거 같아요)

2024-11-26 17:16 UTC, anxi01 commented on src/main/java/spring/backend/core/infrastructure/persistence/interceptor/SequentialUUID.java
> +@Target({ElementType.METHOD, ElementType.FIELD})
보통 엔티티의 ID를 생성할 때 사용할 거 같은데 필드에만 적용해도 되지 않을까요?

2024-11-27 05:59 UTC, HoyeongJeon commented on src/main/java/spring/backend/core/infrastructure/persistence/interceptor/SequentialUUID.java
> +public @interface SequentialUUID {
persistence/shared

여기 두는게 좋을거같아요~!

2024-11-27 06:00 UTC, HoyeongJeon commented on src/main/java/spring/backend/core/infrastructure/persistence/interceptor/SequentialUUID.java
> +@Target({ElementType.METHOD, ElementType.FIELD})
수정하겠습니다!

2024-11-27 08:58 UTC, anxi01 approved these changes
고생하셨습니당

2024-11-28 03:13 UTC, merged