Fix/#155 delete keyword nature
KUSITMS-30th-TEAM-C/backend pull request #156
Opened 2024-11-27 05:57 UTC by HoyeongJeon

## ✅ PR 유형
어떤 변경 사항이 있었나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

---

## 📝 작업 내용

- Keyword에서 NATURE를 삭제했습니다.
- ONLINE_AND_OFFLINE 시 OFFLINE 요청에 SOCIAL이 들어 온 경우, SOCIAL만 걸러내는 로직을 작성했습니다.
- ClovaStudio 응답에서 파싱용 PATTERN을 수정했습니다.
- 가끔 클로바가 추천 활동의 키워드를 여러개 주는 경우가 있습니다. 응답의 키워드가 여러개일 경우, 키워드를 분리하고 랜덤한 하나의 키워드만 전달하도록 바꿨습니다.

---

## ✏️ 관련 이슈

- Fixes : #155 

---

## 🎸 기타 사항 or 추가 코멘트

2024-11-27 09:21 UTC, anxi01 requested changes
```java
public record UserMonthlyActivityDetail(

        @Schema(description = "활동 카테고리 \n\n SELF_DEVELOPMENT(자기개발), HEALTH(건강), NATURE(자연), CULTURE_ART(문화/예술), ENTERTAINMENT(엔터테인먼트), RELAXATION(휴식), SOCIAL(소셜)",
                example = "SELF_DEVELOPMENT")
        Category category,
```
여기도 제거 부탁드려요!

2024-11-27 09:21 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/application/GetRecommendationsFromClovaService.java
> -            throw ClovaErrorCode.ONLINE_TYPE_CONTAIN_NATURE.toException();
`ClovaErrorCode.ONLINE_TYPE_CONTAIN_NATURE` 도 제거해주세요~

2024-11-27 09:21 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/application/GetRecommendationsFromClovaService.java
> +        int randomIdx = new Random().nextInt(validKeywords.size());
Random 객체를 static final 객체로 만들어서 매번 새로운 객체 생성이 아닌 한 번 생성하고 재사용하는게 좋을 거 같아요

2024-11-27 09:21 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/application/GetRecommendationsFromClovaService.java
> +                .filter(this::isValidKeyword)
q) split하고 trim으로 공백 제거 안해도 괜찮을까요?

2024-11-28 04:23 UTC, HoyeongJeon commented on src/main/java/spring/backend/recommendation/application/GetRecommendationsFromClovaService.java
> -            throw ClovaErrorCode.ONLINE_TYPE_CONTAIN_NATURE.toException();
확인했습니다.

2024-11-28 04:42 UTC, HoyeongJeon commented on src/main/java/spring/backend/recommendation/application/GetRecommendationsFromClovaService.java
> +                .filter(this::isValidKeyword)
엇 이 부분을 빠뜨렸네요

2024-11-28 05:24 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/application/GetRecommendationsFromClovaService.java
> +    private final Random RANDOM = new Random();
static final로 객체 생성해주세요

2024-11-28 05:36 UTC, anxi01 approved these changes
고생하셨습니다!

2024-11-28 07:33 UTC, merged