Feat: refreshToken을 Redis에 저장한다.
KUSITMS-30th-TEAM-C/backend pull request #29
Opened 2024-10-18 04:15 UTC by HoyeongJeon

## ✅ PR 유형
어떤 변경 사항이 있었나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

---

## 📝 작업 내용

- RedisSerivce를 구현했습니다.
- refreshToken이 저장될 때 Redis에 저장됩니다.
- RedisServiceTest를 작성해 refreshToken이 Redis에 저장되는지 Test를 작성했습니다.
- Redis 관련 에러를 GlobalErrorCode에 추가했습니다.
- Redis의 경우 NCP를 사용하면 비용이 많이 나가 , docker-compose를 통해 띄우도록 변경했습니다.
- 서버에서도 docker-compose를 통해 서비스가 실행되도록 변경했습니다.  

---

## ✏️ 관련 이슈

- Resolves : #28 

---

## 🎸 기타 사항 or 추가 코멘트

2024-10-18 18:57 UTC, anxi01 commented on docker-compose-local.yml
> +      - '3307:3306'
q) mysql은 왜 띄우는 걸까요??
이미 로컬에서 작동하고 있는데 이유가 있는지 궁금합니다

2024-10-18 19:01 UTC, anxi01 commented on src/main/java/spring/backend/core/application/JwtService.java
> +    private final RedisService redisService;
JwtService의 경우, 공통으로 사용하는 유틸성 클래스에 가까운데,
여기서 RedisService를 주입 받아 사용하는건 결합도가 높아진다고 생각합니다

JwtService는 말 그대로 Jwt를 생성하거나 조회하는 등의 단위적인 작업을 진행하면 좋을 거 같습니다.
따라서 아래 RefreshToken 생성은 JwtService에서 진행하고, redis에 저장하는 작업은 RedisService에서 진행하는게 좋을 거 같습니다

2024-10-18 19:16 UTC, anxi01 commented on src/main/java/spring/backend/core/application/JwtService.java
> +    private final RedisService redisService;
JwtService의 경우, 공통으로 사용하는 유틸성 클래스에 가까운데,
여기서 RedisService를 주입 받아 사용하는건 결합도가 높아진다고 생각합니다

JwtService는 말 그대로 Jwt를 생성하거나 조회하는 등의 단위적인 작업을 진행하면 좋을 거 같습니다.
따라서 아래 RefreshToken 생성은 JwtService에서 진행하고, redis에 저장하는 작업은 RedisService에서 진행하는게 좋을 거 같습니다.
그리고 Auth 디렉토리에서 RefreshTokenService를 만들어서 JwtService와 RedisService를 의존받아 사용하는게 어떨까 싶습니다.

2024-10-18 19:21 UTC, anxi01 commented on src/main/java/spring/backend/core/application/RedisService.java
> +    public TimeUnit convertChronoUnitToTimeUnit(ChronoUnit chronoUnit) {
외부 클래스에서 사용하지 않으면 private으로 현재 클래스에서만 사용하게 하면 좋을 거 같아요!

2024-10-18 19:24 UTC, anxi01 commented on src/main/java/spring/backend/core/infrastructure/redis/repository/RedisRepository.java
> +public class RedisRepository {
현재 RedisRepository는 RefreshToken의 기능을 제공합니다.
RedisRepository보다 RefreshRepository가 더 낫지 않을까요??

2024-10-18 19:41 UTC, anxi01 commented on src/main/java/spring/backend/core/exception/error/GlobalErrorCode.java
> +  UNSUPPORTED_TYPE(HttpStatus.BAD_REQUEST, "올바르지 않은 타입입니다.");
UNSUPPORTED_TYPE의 의미가 애매한 거 같아요..!
좀 더 자세하면 좋을 거 같습니다!
추가로, 만약 위에 코드들을 Auth 패키지로 옮길 수 있다면 AuthenticationErrorCode에 적용하는 것도 좋아 보입니다!
(GlobalErrorCode는 말 그대로 전역 에러 코드라 특정 기술에서 파생되는 에러보다는 진짜 기초적인 에러코드라 생각하시면 좋을 거 같아요!)

2024-10-18 19:42 UTC, anxi01 commented on src/main/java/spring/backend/core/application/RedisService.java
> +    private final RedisRepository redisRepository;
DDD에서 DIP(의존 역전 원칙)으로 저수준 모듈(인프라, 외부 기술, 여기서는 레디스)이 고수준 모듈(단순 Repostiory)에 의존하도록 바꾼다고 간단하게 생각하시면 좋습니다
저수준 모듈이 고수준 모듈에 의존하기 위해서 추상화한 인터페이스를 사용합니다

그래서 RefreshTokenRepository를 고수준 모듈로 도메인 내의 Repository에 생성하고, 저수준 모듈인 RefreshTokenRedisRepository를 생성해서 고수준인 RefreshTokenRepository을 의존하여 구현하면 어떨까 싶습니다.

`RefreshTokenRepository - domain.repository`
```
public interface RefreshTokenRepository {
  void save();
  RefreshToken findByMemberId();
}
```

`RefreshTokenRedisRepository - infrastructure.redis.repository`
```
public class RefreshTokenRedisRepository implements RefreshTokenRepository {

  @Override
  ... (구현)
}
```
이런 식으로 하면 어떨까 싶습니다! 
만약 이렇게 하게 되면 Redis의 외부 기술과 분리할 수 있고, 그렇다면 auth 패키지에 domain 패키지와 infrastructure 패키지에 넣어서 auth 패키지 내에서 사용할 수 있지 않을까 싶어요!

그래서 위와 같이 적용한다면
auth의 application 패키지에서 위 redisService를 RefreshTokenService로 수정해서 auth 내에서 유지보수할 수 있지 않을까요??

2024-10-18 19:55 UTC, anxi01 commented on src/main/java/spring/backend/core/configuration/redis/RedisConfiguration.java
> +        return new LettuceConnectionFactory(new RedisStandaloneConfiguration(host, port));
q) RedisStandaloneConfiguration로 객체를 생성해서 넣으신 이유가 있을까요??

2024-10-18 19:59 UTC, anxi01 commented on src/main/java/spring/backend/core/configuration/redis/RedisConfiguration.java
> +    public RedisTemplate<?, ?> redisTemplate() {
제네릭으로 구현한 거 좋은 거 같아요!! 여러 타입을 받을 수 있는게 좋아 보이네요!

2024-10-18 20:07 UTC, anxi01 requested changes
고생하셨습니다!
Redis를 사용해서 저장해보지 않았는데 이번 리뷰를 계기로 어떤 식으로 사용하는지 알게됐네요!!
코드의 리뷰보다는 DDD 및 모듈 구조에 관련한 리뷰를 남겼습니다!
오늘 대면으로 만나니까 대면에서 얘기 나눠봐도 좋을 거 같아요~!

2024-10-19 01:43 UTC, HoyeongJeon commented on docker-compose-local.yml
> +      - '3307:3306'
개발당시 docker-compose로 돌렸을 때 계속 mysql db 연결 에러가 발생해  docker-copomse로 띄웠는데, 다시 돌려보니 이번엔 잘되네요 ;.; 
다시 빼버리고, application.yml(도커 컴포즈용) 업로드할게요

2024-10-19 05:37 UTC, anxi01 commented on docker-compose-local.yml
> +      - '3307:3306'
좋아요!

2024-10-19 13:00 UTC, HoyeongJeon commented on src/main/java/spring/backend/core/configuration/redis/RedisConfiguration.java
> +        return new LettuceConnectionFactory(new RedisStandaloneConfiguration(host, port));
```java
        return new LettuceConnectionFactory(host, port);
```
위와 같은 방식으로 생성하면 defaultt 세팅으로 Redis가 생성이 됩니다. 그러나 hostname이나 redis password가 있을 경우 세팅을 할 수 없습니다. 
https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/connection/lettuce/LettuceConnectionFactory.html#%3Cinit%3E()

```java
        return new LettuceConnectionFactory(new RedisStandaloneConfiguration(host, port));
```
안에 RedisStandaloneCOnfiguration을 사용하면 host,port 뿐 아니라 hostname, password , username 등 더 많은 정보를 커스텀할 수 있습니다.

확장성을 고려해 RedisStandaloneConfiguration을 사용했습니다. 

추가적으로 
```java
    @Bean
    public LettuceConnectionFactory redisConnectionFactory() {
        RedisStandaloneConfiguration configuration = new RedisStandaloneConfiguration();
        configuration.setHostName(host);
        configuration.setPort(port);
        configuration.setPassword("password");
        configuration.getDatabase(database); // 데이터베이스 번호
        return new LettuceConnectionFactory(configuration);
    }
```
이런식으로 사용할 수 있습니다. 

etc)
Redis는 기본적으로 16개의 db 서버를 제공해줍니다. 
기본은 0번 데이터베이스를 사용하지만 타 애플리케이션과 겹치지 않기 위해 다른 데이터베이스를 설정하고 싶다면 setDatabase()를 통해 다른 데이터베이스 번호를 지정하면 됩니다 .

https://github.com/redis/redis/blob/unstable/redis.conf#L165
![image](https://github.com/user-attachments/assets/332e5e41-9c02-432a-aaf1-29343b5e22ff)

2024-10-19 14:04 UTC, anxi01 commented on src/main/java/spring/backend/auth/application/RefreshTokenService.java
> +            throw GlobalErrorCode.REDIS_CONNECTION_ERROR.toException();
금일 대면 리뷰에서 GlobalErrorCode 대신 AuthenticationErrorCode를 사용하기로 했으니 
이 클래스에 `REDIS_CONNECTION_ERROR` 는 AuthenticationErrorCode의 에러 코드를 사용하고,
GlobalErrorCode는 제거하는게 좋을 거 같습니다!

2024-10-19 14:05 UTC, anxi01 commented on src/main/java/spring/backend/auth/domain/repository/RefreshTokenRepository.java
> +    String findById(UUID memberId);
`findById`보다 `findByMemberId`가 더 직관적일 거 같아요!

2024-10-19 14:14 UTC, HoyeongJeon commented on src/main/java/spring/backend/auth/application/RefreshTokenService.java
> +            throw GlobalErrorCode.REDIS_CONNECTION_ERROR.toException();
헉 바로 수정하겠습니다.

2024-10-19 14:52 UTC, anxi01 approved these changes
고생 많으셨습니다!

2024-10-19 14:58 UTC, merged