Feat: (#34) 온보딩에서 사용자 가입 API를 구현한다
KUSITMS-30th-TEAM-C/backend pull request #51
Opened 2024-10-22 10:06 UTC by anxi01

## ✅ PR 유형
어떤 변경 사항이 있었나요?

- [x] 새로운 기능 추가
- [ ] 버그 수정
- [x] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

---

## 📝 작업 내용
- 온보딩에서 사용자 가입 API를 구현했습니다.
- 멤버 도메인 모델을 가변 객체로 변경했습니다.
  - 밸류 타입이 불변 객체여야 하는데 도메인 모델까지 불변 객체로 생성했어서 이 부분은 수정했습니다.
- SpringValidation을 사용할 때 에러 메시지의 폼이 달라서 GlobalExceptionHandler에 추가해 에러 메시지를 통일하였습니다.
- 여러 곳에서 사용하는 기능을 모은 MemberService를 MemberServiceHelper로 클래스명을 변경했습니다. ([헬퍼 클래스란?](https://epdev.tistory.com/46))

---

## ✏️ 관련 이슈
- Resolves : #34 
---

## 🎸 기타 사항 or 추가 코멘트
- 프로필 이미지는 NCP Object Storage에 저장하여 URL을 이용하여 사용하려고 합니다.
  - 사용자가 직접 업로드하는 것이 아닌 우리가 제공한다
  - NCP에 사진을 저장해야한다.
  - 프론트와 url을 공유해야한다.

2024-10-23 02:57 UTC, HoyeongJeon commented
기능별 서비스와 컨트롤러를 만들고, 공통적으로 제공하는 기능은 Helper 클래스로 묶는 방식으로 통일할까요?

2024-10-23 03:18 UTC, HoyeongJeon commented on src/main/java/spring/backend/auth/application/OnboardingSignUpService.java
> +        if (member == null || member.isMember()) {
유효성 검사를 분리하는 것은 어떻게 생각하시나요 ? 
``` java
public Member onboardingSignUp(Member member, OnboardingSignUpRequest request) {
        validateMember(member);
        validateRequest(request);
        validateBirthYear(request);

        member.convertGuestToMember(
                request.nickname(),
                request.birthYear(),
                request.gender(),
                request.profileImage()
        );

        return memberServiceHelper.save(member);
    }

    private void validateMember(Member member) {
        if (member == null || member.isMember()) {
            로직 ...
        }
    }

    private void validateRequest(OnboardingSignUpRequest request) {
        if (request == null) {
            로직 ...
        }
    }
```
위 방식이나 , 

``` Java
public Member onboardingSignUp(Member member, OnboardingSignUpRequest request) {
        validateMemberAndRequest(member, request);

        member.convertGuestToMember(
                request.nickname(),
                request.birthYear(),
                request.gender(),
                request.profileImage()
        );

        return memberServiceHelper.save(member);
    }
    
    private void validateMemberAndRequest(Member member, OnboardingSignUpRequest request) {
        validateMember(member);
        validateRequest(request);
        validateBirthYear(request);
        
    }

    private void validateMember(Member member) {
        if (member == null || member.isMember()) {
            로직 ...
        }
    }

    private void validateRequest(OnboardingSignUpRequest request) {
        if (request == null) {
            로직 ...
        }
    }
    
    private boolean validateBirthYear(OnboardingSignUpRequest request) {
        if (request.birthYear() == null) {
            로직 ...
        }
    }
```

이런식으로요!
메서드가 본인의 역할에 더욱 집중하게 되고 가독성도 더 좋아지지 않을까? 생각해서 달았습니다.

2024-10-23 03:18 UTC, HoyeongJeon commented on src/main/java/spring/backend/auth/application/OnboardingSignUpService.java
> +        return birthYear >= (currentYear - BIRTH_YEAR_RANGE) && birthYear <= currentYear;
이 부분을 void로 반환하고 내부에서 에러처리하는 것은 어떻게 생각하시나요 ??

```Java
    private void validateBirthYear(OnboardingSignUpRequest request) {
        int birthYear = request.birthYear();
        int currentYear = Year.now().getValue();
        if (birthYear < (currentYear - BIRTH_YEAR_RANGE) || birthYear > currentYear) {
            log.error("[OnboardingSignUpService] Invalid request birth year.");
            throw AuthenticationErrorCode.INVALID_BIRTH_YEAR.toException();
        }
    }
```

일단은 유효성 검사를 따로 분리해서 생각했을 때 예시입니다. 
분리한다면 이 부분도 void로 바꾸고, 내부에서 에러처리하는 것이 통일성있다 생각했어요!

2024-10-23 03:23 UTC, HoyeongJeon commented on src/main/java/spring/backend/member/application/MemberServiceHelper.java
> +    public Member save(Member member) {
Helper 클래스가 생겼으니, 
CreateMemberWithOAuthService 내부의 memberRepository.save() 로 쓰이는 부분들도 헬퍼 클래스를 쓸 수 있겠네요! 
```Java
Member savedMember = memberRepository.svae()
```
이런 부분들이요! 
이미 바뀐것인지, 제가 못찾은건지 모르겠네요 .. 

그 외에도 CreateMemberWithOAuthService 내부 코드를 보면 
memberRepsitory를 그대로 사용하는 코드들이 있는데, 이런 부분들도 헬퍼 클래스로 빼는 것은 어떨까요? 
이게 좋은 방법인지는 모르겠네요..

2024-10-23 04:58 UTC, HoyeongJeon commented
고생하셨습니다~!

2024-10-23 06:16 UTC, anxi01 commented on src/main/java/spring/backend/member/application/MemberServiceHelper.java
> +    public Member save(Member member) {
사실 헬퍼 클래스를 만든 이유는 개별 도메인에서 외부 도메인의 다른 계층을 의존할 때 (여기서는 `Member-Domain(Repository)` 와 `Auth-application` ) 다른 계층이 아닌 동일 계층에서 의존하면 어떨까해서 헬퍼 클래스를 만들고 헬퍼 클래스 내의 메서드는 외부 도메인에서 사용하는 것을 구현하였습니다.
지금 고민인게 
1. A 도메인의 애플리케이션 계층에서 B 도메인의 도메인계층의 Repository를 의존하면 안되나? (같은 도메인에서는 애플리케이션 계층과 도메인 리포지터리 계층이 의존하기  때문)
2. 외부 도메인에서 사용하는 로직을 헬퍼 클래스에 모아두면 위 리뷰처럼 동일 도메인에서의 repository의 메서드를 헬퍼로 변경해야하는가?
이런 고민이 있습니다.

생각 중인 해결책은 
- 인프라스트럭처의 repository를 가져오는게 아닌 도메인의 repository를 의존하는 거니 그냥 헬퍼를 없애고 repository를 의존할까..
- 작은 단위의 기능(findById()) 도 응용 계층에 단일 책임을 갖는 클래스로 분리할까..

이정도가 생각나는데 
지금 가장 끌리는건 첫 번째 해결책인 헬퍼 클래스를 없애고, repository를 의존하는 방법입니다.
처음 얘기했을 때는 같은 계층끼리 최대한 의존을 하자고 했지만, repository를 의존하는게 안좋은 방식은 아니에요!
단순히 저는 같은 계층에서 의존하는게 레이어를 더 잘 살릴 수 있지 않을까 했는데..
헬퍼 클래스를 없애고 repository를 의존하는건 어떻게 생각하세요??

2024-10-23 06:17 UTC, anxi01 commented on src/main/java/spring/backend/member/application/MemberServiceHelper.java
> +    public Member save(Member member) {
헬퍼 클래스를 만들면 위의 리뷰처럼 혼란이 많이 올 거 같고, DDD 책에서도 외부 도메인에서 리포지토리를 의존하더라고요!
(제가 같은 계층끼리 최대한 의존하자고 했는데 혼동 일으켜서 죄송합니다ㅜㅜ)

2024-10-23 06:29 UTC, anxi01 commented on src/main/java/spring/backend/auth/application/OnboardingSignUpService.java
> +        if (member == null || member.isMember()) {
메서드로 만드는거 좋네요!
사실 도메인 로직보다 검증 로직이 더 많았는데 메서드로 분리하니 깔끔하고 좋은 거 같습니다

2024-10-23 07:44 UTC, HoyeongJeon commented on src/main/java/spring/backend/member/application/MemberServiceHelper.java
> +    public Member save(Member member) {
만약 헬퍼 클래스가 다른 도메인의 Repository에 접근하는 것을 우선으로 만든 것이라면 없어도 괜찮다고 생각합니다.

```
헬퍼 클래스를 만들면 위의 리뷰처럼 혼란이 많이 올 거 같고
```

개발을 편하게 만들고 소통을 편하게 만들기 위해 도입한 내용이 소통에 불편함을 만들면 지금은 불필요한게 될 수 있을거같아요...!

계속 구글링을 해봤는데, 다른 도메인의 레포지토리에 접근하는 것이 안좋다는 내용을 찾지 못했고, 책에서도 그렇게 나온다면 타 도메인의 레포지토리에 의존하는게 문제 없지 않을까요 ..! 

저는 현재는 헬퍼 클래스 대신 레포지토리를 사용하는게 현 상황에서는 좋다 생각합니다.

추후에 여러 도메인 로직 간 상호작용을 좀 더 편하게 하기위해 헬퍼 클래스를 도입해야한다면 그 때 도입하는 것이 더 좋다고 생각합니다. 

클로바 API 호출이 다양한 도메인에서 공통적으로 사용되면 이를 헬퍼로 빼도 될거같아요 (이러면 core에 넣어야 하나요?)

2024-10-23 07:47 UTC, HoyeongJeon commented on src/main/java/spring/backend/member/application/MemberServiceHelper.java
> +    public Member save(Member member) {
Core 안에 util이나 helper를 넣는 것은 DDD를 위반하는건지 궁금합니다.

2024-10-23 07:47 UTC, HoyeongJeon requested changes

2024-10-23 07:47 UTC, HoyeongJeon commented on src/main/java/spring/backend/member/application/MemberServiceHelper.java
> +    public Member save(Member member) {
Core 안에 util이나 helper를 넣는 것은 DDD를 위반하는건지 궁금합니다.

2024-10-23 11:02 UTC, anxi01 commented on src/main/java/spring/backend/member/application/MemberServiceHelper.java
> +    public Member save(Member member) {
> 저는 현재는 헬퍼 클래스 대신 레포지토리를 사용하는게 현 상황에서는 좋다 생각합니다.

그러면 리포지터리를 의존하는 걸로 하고 헬퍼 클래스는 제거하도록 하겠습니다.
헬퍼 클래스는 우선 보류하면 될 거 같아요

2024-10-23 11:03 UTC, anxi01 commented on src/main/java/spring/backend/member/application/MemberServiceHelper.java
> +    public Member save(Member member) {
> 클로바 API 호출이 다양한 도메인에서 공통적으로 사용되면 이를 헬퍼로 빼도 될거같아요 (이러면 core에 넣어야 하나요?)

클로바 API는 외부 모듈로써 인프라스트럭처 단에 존재해야합니다.
헬퍼는 말 그대로 도와주는 클래스라서, 예를 들면

2024-10-23 11:12 UTC, anxi01 commented on src/main/java/spring/backend/member/application/MemberServiceHelper.java
> +    public Member save(Member member) {
> Core 안에 util이나 helper를 넣는 것은 DDD를 위반하는건지 궁금합니다.

제가 이해한 헬퍼 클래스는 도메인에서 중복되는 로직을 모아 놓은 클래스입니다.
```
public final class MemberServiceHelper { 

    public Member findByExistingMember(UUID memberId) {
        ... 
    }
}
```
따라서 헬퍼 클래스는 도메인의 응용 계층에 존재해야한다고 생각합니다.

반면 util 클래스는 도메인과 무관한 일반적인 기술적 기능을 제공하는 클래스입니다.
만약 문자열 처리를 해야한다면 여러 클래스에서 문자열을 처리하는 로직을 추가하는게 아닌 유틸 클래스에 모아 놓고 사용할 수 있습니다.

따라서 유틸 클래스는 core에 들어가도 된다고 생각합니다.

2024-10-23 13:25 UTC, HoyeongJeon commented on src/main/java/spring/backend/member/application/MemberServiceHelper.java
> +    public Member save(Member member) {
네~ 이해했습니다~!

2024-10-23 13:25 UTC, HoyeongJeon requested changes
그러면 helper 대신 repository로 작업해요~!

2024-10-24 06:54 UTC, HoyeongJeon approved these changes
LGTM~!

2024-10-24 07:51 UTC, merged