Chore: (#50) Clova API를 연동한다.
KUSITMS-30th-TEAM-C/backend pull request #57
Opened 2024-10-28 08:13 UTC by HoyeongJeon

## ✅ PR 유형
어떤 변경 사항이 있었나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

---

## 📝 작업 내용

- 클로바 스튜디오와 서비스를 연동했습니다. 

### 요청과 응답

<img width="1225" alt="image" src="https://github.com/user-attachments/assets/e76f091b-f41d-4d06-ae3a-8ea8b25e9107">

---

## ✏️ 관련 이슈
- Fixes : #50 

---

## 🎸 기타 사항 or 추가 코멘트
- 응답이 중구난방으로 옵니다. 이게 현재 가장 큰 문제입니다. 응답의 틀을 정하려해도 어쩔땐 응답이 이상하게 오기도 하는데 이를 어떻게 해결해야할지 모르겠어요.
- 현재 구현이 다 끝난 것은 아닙니다. 일단 연동은 여기서 끝내고, 추후 응답 틀 변경과 추천 로직을 더 상세하게 만드는 부분은 새로운 이슈를 파서 하는게 나을까요?

2024-10-29 02:22 UTC, anxi01 commented on src/main/java/spring/backend/core/configuration/webclient/WebClientConfiguration.java
> +    public WebClient webClient(WebClient.Builder builder) {
WebClient를 매개변수로 받아서 사용하는 것보다 메서드 내부에서 구현하는게 어떨까요?
매개변수에 WebClient.Builder를 의존하는 이유가 있을까요??

```
@Bean
public WebClient webClient() {
    return WebClient.builder()
            .defaultHeaders(httpHeaders -> {
                httpHeaders.set("X-NCP-CLOVASTUDIO-API-KEY", apiKey);
                httpHeaders.set("X-NCP-APIGW-API-KEY", apiGatewayKey);
                httpHeaders.setContentType(MediaType.APPLICATION_JSON);
            })
            .build();
}
```

2024-10-29 04:53 UTC, anxi01 requested changes
클로바 연동하시느라 고생 많으셨습니다!
리뷰 확인해보시고 궁금하신 점 있음 답글 달아주세요~

추가로 수정하시기 전에
git pull dev
git rebase dev 해주세요!!

2024-10-29 04:53 UTC, anxi01 commented on src/main/java/spring/backend/core/configuration/webclient/WebClientConfiguration.java
> +    public WebClient webClient(WebClient.Builder builder) {
WebClient를 매개변수로 받아서 사용하는 것보다 메서드 내부에서 구현하는게 어떨까요?
매개변수에 WebClient.Builder를 의존하는 이유가 있을까요??

```
@Bean
public WebClient webClient() {
    return WebClient.builder()
            .defaultHeaders(httpHeaders -> {
                httpHeaders.set("X-NCP-CLOVASTUDIO-API-KEY", apiKey);
                httpHeaders.set("X-NCP-APIGW-API-KEY", apiGatewayKey);
                httpHeaders.setContentType(MediaType.APPLICATION_JSON);
            })
            .build();
}
```

2024-10-29 04:53 UTC, anxi01 commented on src/main/java/spring/backend/core/configuration/webclient/WebClientConfiguration.java
> +    public WebClient webClient(WebClient.Builder builder) {
현재 WebClient 빈은 NCP ClovaStudio 설정에 관한 WebClient이므로
webClient보다 clovaWebClient나 clovaStudioWebClient로 빈을 설정하는게 낫지 않을까요??

나중에 다른 서비스를 위한 WebClient가 추가될 수 있기 때문에, 빈의 이름을 구체화하는게 좋을 거 같아요

2024-10-29 04:53 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/infrastructure/clova/domain/value/Type.java
> +public enum Type {
현재 dev 브랜치로 최신화 및 리베이스하셔서 
활동 도메인의 Type을 사용해주세요~

2024-10-29 04:53 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/infrastructure/clova/dto/request/Message.java
> +        if (activityType.equals("OFFLINE")) {
String equals() 비교하실 때, 
`객체.equals(문자열)` 은 객체가 null일 때 NPE 발생할 수 있습니다

따라서 `문자열.equals(객체)` 로 사용하시는게 NPE를 방지할 수 있습니다

2024-10-29 04:53 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/presentation/RequestRecommendationsFromClovaController.java
> +    public ResponseEntity<RestResponse<List<ClovaRecommendationResponse>>> requestRecommendations(@RequestBody UserInputRequest userInputRequest) {
@Valid를 붙여야 request의 Spring Validation이 적용됩니다

2024-10-29 04:53 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/dto/request/UserInputRequest.java
> +    private String keyword;
Keyword도 활동 도메인의 Keyword 밸류타입을 사용해주세요~

2024-10-29 04:53 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/dto/request/UserInputRequest.java
> +    private int spareTime;
int는 기본값이 0이라 @NotNull이 필요 없습니다
Integer로 변경하는건 어떨까요??

2024-10-29 04:53 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/infrastructure/clova/application/ClovaService.java
> +public class ClovaService {
DIP를 적용해보면 좋을 거 같습니다.

`GetRecommendationsFromClovaService` 서비스에서 ClovaService를 의존하지 않고
`RecommendationProvider` 라는 추상 인터페이스를 만들고 이 추상 인터페이스는 응용 계층에 존재합니다.

그리고 RecommendationProvider내 
`String requestToClovaStudio(UserInputRequest userInputRequest)` 메서드를 만들고 

infrastructure에 `ClovaRecommendationProvider`와 같이 구현체를 만들면 더욱 DDD에 부합한 설계라고 생각합니다.

응용 계층 : `GetRecommendationsFromClovaService`-> `RecommendationProvider` 
인프라 계층 : `ClovaRecommendationProvider`

도메인주도설계 시작하기의 챕터 2부분 참고해주세요~

2024-10-29 04:53 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/infrastructure/clova/application/ClovaService.java
> +                throw ClovaErrorCode.NULL_RESPONSE_FROM_CLOVA.toException();
여기서 클로바 에러 처리를 하지 않고 `GetRecommendationsFromClovaService` 에서 에러처리하는건 어떨까요?

여기서는 WebClientException과 Exception인 전역 에러를 처리하고 비즈니스로직에서 클로바 도메인 에러를 처리하면 어떨까 했습니다!

2024-10-29 04:53 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/infrastructure/clova/dto/request/Message.java
> +        system, user
열거 상수는 대문자로 작성해주세요!

2024-10-29 04:53 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/infrastructure/clova/dto/request/Message.java
> +        String content = "너는 자투리시간과 활동의 타입(온라인,오프라인, 둘다)를 받고, 키워드와 위치 정보를 받아 사용자에게 5가지의 활동을 추천해주는 봇이야. 추천목록만 보내주면 되고, 각 추천목록은 줄바꿈으로 구분해줘. 추천목록을 제외한 잡설은 보내지마.";
`private static final String SYSTEM_MESSAGE_CONTENT = "너는 자투리시간과 활동의 타입(온라인,오프라인, 둘다)를 받고, 키워드와 위치 정보를 받아 사용자에게 5가지의 활동을 추천해주는 봇이야. 추천목록만 보내주면 되고, 각 추천목록은 줄바꿈으로 구분해줘. 추천목록을 제외한 잡설은 보내지마.";`

클래스 로드 시 한 번 초기화되고 변경되지 않으므로 상수로 사용하는게 어떨까요?

2024-10-29 04:53 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/infrastructure/clova/dto/request/Message.java
> +        if (activityType.equals("OFFLINE")) {
offline 검증 로직을 메서드로 추출하는건 어떨까요?

2024-10-29 04:53 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/dto/request/UserInputRequest.java
> +public class UserInputRequest {
클래스명을 좀 더 구체화하면 좋을 거 같습니다!

2024-10-29 04:53 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/presentation/RequestRecommendationsFromClovaController.java
> +public class RequestRecommendationsFromClovaController {
저희가 각 기능 별로 서비스와 컨트롤러를 만들잖아요!
지금 저희가 만든 서비스와 컨트롤러를 보면 서비스에서의 기능명을 컨트롤러도 동일하게 사용하고 있으니
(`RotateAccessTokenService`, `RotateAccessTokenController`)

`GetRecommendationsFromClovaController`는 어떨까요??

2024-10-29 04:53 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/dto/request/UserInputRequest.java
> +    @Pattern(regexp = "^(5|[1-9][0-9]|[1-2][0-9]{2}|300)$", message = "자투리 시간은 5부터 300 사이의 숫자로 입력해주세요.")
Pattern은 문자열 정규표현식 검증할 때 사용한다고 알고 있는데 숫자도 사용가능한가요??
저는 숫자는 @Min @Max를 사용한다고 알고 있어서요!

2024-10-29 04:53 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/infrastructure/clova/dto/request/ClovaRequest.java
> +                .build();
```
    private static final double DEFAULT_TOP_P = 0.8;
    private static final int DEFAULT_TOP_K = 0;
    private static final int DEFAULT_MAX_TOKENS = 500;
    private static final double DEFAULT_TEMPERATURE = 0.5;
    private static final double DEFAULT_REPEAT_PENALTY = 5.0;
    private static final boolean DEFAULT_INCLUDE_AI_FILTERS = true;
    private static final int DEFAULT_SEED = 0;
```
숫자 값들도 상수로 만드는게 좋을 거 같아요!

2024-10-29 04:53 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/application/GetRecommendationsFromClovaService.java
> +        String[] recommendations = result.split("\n");
"\n"도 상수 처리해주면 추후 수정에 용이할 거 같습니다! 의미 파악도 되고요!

2024-10-29 04:53 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/infrastructure/clova/dto/request/Message.java
> +            return "자투리 시간: " + spareTime + "분\\n선호활동: " + activityType + "\\n활동 키워드: " + keyword + "\\n위치 : " + location + "\\n \\n활동 추천해줘\\n\\n";
```return String.format("자투리 시간: %d분\n선호활동: %s\n활동 키워드: %s\n위치: %s\n\n활동 추천해줘\n\n", spareTime, activityType, keyword, location);```

와 같이 String.format을 사용하면 변수를 관리할 때 더 보기 좋을 거 같아요!

2024-10-29 05:17 UTC, HoyeongJeon commented on src/main/java/spring/backend/recommendation/dto/request/UserInputRequest.java
> +    private int spareTime;
엇 감사합니다~!

2024-10-29 05:18 UTC, HoyeongJeon commented on src/main/java/spring/backend/recommendation/dto/request/UserInputRequest.java
> +public class UserInputRequest {
UserInputRequest에서 ClovaRecommendationRequest로 변경했습니다.

2024-10-29 05:18 UTC, HoyeongJeon commented on src/main/java/spring/backend/recommendation/dto/request/UserInputRequest.java
> +    @Pattern(regexp = "^(5|[1-9][0-9]|[1-2][0-9]{2}|300)$", message = "자투리 시간은 5부터 300 사이의 숫자로 입력해주세요.")
제가 잘못사용했네요.
다시 고쳤습니다~!

2024-10-29 05:27 UTC, HoyeongJeon commented on src/main/java/spring/backend/recommendation/infrastructure/clova/dto/request/ClovaRequest.java
> +                .build();
수정했습니다~!

2024-10-29 05:28 UTC, HoyeongJeon commented on src/main/java/spring/backend/recommendation/application/GetRecommendationsFromClovaService.java
> +        String[] recommendations = result.split("\n");
수정했습니다~!

2024-10-29 06:34 UTC, HoyeongJeon commented on src/main/java/spring/backend/recommendation/infrastructure/clova/dto/request/Message.java
> +        system, user
Clova Studio에 요청을 보낼 때 ROLE을 대문자로 보내게 되면 에러가 발생합니다. 
그래서 생각한 방법이 현재 코드와 같이 소문자로 enum을 정의한 것입니다. 
이를 대문자로 바꾸면 아래와 같은 방법을 사용하려는데 괜찮을까요 ? 

```Java

    private String role;
    private String content;

    @RequiredArgsConstructor
    public enum ROLE {
        SYSTEM("system"), USER("user");
        private final String description;

        @Override
        public String toString() {
            return description;
        }
    }

    public static Message createSystem() {
        return Message.builder()
                .role(ROLE.SYSTEM.toString())
                .content(DEFAULT_SYSTEM_CONTENT)
                .build();
    }
}

```

2024-10-29 06:44 UTC, HoyeongJeon commented on src/main/java/spring/backend/recommendation/infrastructure/clova/dto/request/Message.java
> +        if (activityType.equals("OFFLINE")) {
수정했습니다~!

2024-10-29 09:12 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/infrastructure/clova/dto/request/Message.java
> +        system, user
넵 좋은데 @Getter를 사용해서 getDescripion()으로 가져오는게 더 직관적일 거 같네요~
아 그리고 
```
 public enum Role // ROLE(X)
```
이것도 변경해야할 거 같아요~

2024-10-30 03:32 UTC, HoyeongJeon commented on src/main/java/spring/backend/core/configuration/webclient/WebClientConfiguration.java
> +    public WebClient webClient(WebClient.Builder builder) {
> WebClient를 매개변수로 받아서 사용하는 것보다 메서드 내부에서 구현하는게 어떨까요?
매개변수에 WebClient.Builder를 의존하는 이유가 있을까요??

코드가 더 깔끔해보인다 생각해서 했었습니다 ㅎㅎ
메서드 내부에서 구현하는 것과 무슨 차이가 있나요?

2024-10-30 04:27 UTC, anxi01 commented on src/main/java/spring/backend/core/configuration/webclient/WebClientConfiguration.java
> +    public WebClient webClient(WebClient.Builder builder) {
빌더 패턴을 사용할 때
```WebClient.builder().필드()....build();```
대부분 이렇게 사용하던거 같아서 이런 식으로 하면 어떨까 했고,

다른 의견으로는 매개변수에 다른 빈을 주입받아서 사용하는 경우는 봤는데
WebClient.Builder를 매개변수에서 주입받아서 사용해야할까? 라는 의문이 들어서요!

메서드 내부에서 구현할 수 있으면 굳이 주입 안받고 내부에서 처리하는게 낫지 않을까 싶습니다!

2024-10-30 04:31 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/application/GetRecommendationsFromClovaService.java
> +    private static final String LF = "\n";
LF가 무슨 뜻인가요??
더 의미를 구체화해서 작성해주셔도 좋을 거 같아요
`LINE_SEPARATOR` 이런 식으로요!

2024-10-30 04:35 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/dto/request/ClovaRecommendationRequest.java
> +    @Min(value = 5, message = "자투리 시간은 5부터 300 사이의 숫자로 입력해주세요.")
자투리 시간 10분 이상 아닌가요??

2024-10-30 04:37 UTC, HoyeongJeon commented on src/main/java/spring/backend/recommendation/application/GetRecommendationsFromClovaService.java
> +    private static final String LF = "\n";
아 "/n"이 Line Feed라서 LF로 했는데, LINE_SEPARATOR가 더 좋네요

2024-10-30 04:38 UTC, HoyeongJeon commented on src/main/java/spring/backend/recommendation/dto/request/ClovaRecommendationRequest.java
> +    @Min(value = 5, message = "자투리 시간은 5부터 300 사이의 숫자로 입력해주세요.")
제가 잘못봤네요 😓

2024-10-30 04:38 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/infrastructure/clova/dto/request/Message.java
> +    public enum ROLE {
`Role`로 변경 부탁드려요~

2024-10-30 07:34 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/infrastructure/clova/application/ClovaRecommendationProvider.java
> +@Service
Provider에서는 비즈니스로직이 따로 존재하지 않아서
@Service보다는 @Component로 붙이는게 좋을 거 같아요!

ClovaService에서 비즈니스 로직을 가지고 Provider에서는 사용만 하는 거니까요!

2024-10-30 07:42 UTC, HoyeongJeon commented on src/main/java/spring/backend/recommendation/infrastructure/clova/application/ClovaRecommendationProvider.java
> +@Service
엇 수정하겠습니다~

2024-10-30 16:27 UTC, HoyeongJeon commented on src/main/java/spring/backend/activity/domain/value/Type.java
> +    ONLINE_AND_OFFLINE("온라인과 오프라인 모두");
AI에게 요청을 보낼 때 "둘 다"라고 보내면 이해를 못하는거 같아서 상세하게 변경했습니다.

2024-10-30 16:28 UTC, HoyeongJeon commented on src/main/java/spring/backend/recommendation/application/GetRecommendationsFromClovaService.java
> +            if (line.matches("^\\d+\\. title :.*")) {
regex 패턴을 상수로 만든 뒤 실행하면 매치를 못해서 하드코딩을 했습니다.
왜 상수로 만들면 동작을 안하는지 모르겠어요..

2024-10-30 17:41 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/application/GetRecommendationsFromClovaService.java
> +            if (line.matches("^\\d+\\. title :.*")) {
정규식을 사용할 때 String 객체의 `matches`를 사용하면
```java
public static Pattern compile(String regex) {
        return new Pattern(regex, 0);
    }
```
정규식을 통해 Pattern 객체를 매번 생성하는 일이 발생하고 이는 for문이 순회될 때마다 불필요한 객체가 반복적으로 생성됩니다.

따라서 String의 `matches` 대신 Pattern을 상수로 1회 초기화 시켜놓고
이를 사용하게 되면 불필요한 객체 생성을 막을 수 있어 성능의 효율을 높일 수 있습니다.

2024-10-30 17:42 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/application/GetRecommendationsFromClovaService.java
> +            if (line.matches("^\\d+\\. title :.*")) {
```java
public class GetRecommendationsFromClovaService {
    private static final String LINE_SEPARATOR = "\n";
    private static final Pattern TITLE_PATTERN = Pattern.compile("^\\d+\\. title :.*");
    private static final Pattern CONTENT_PATTERN = Pattern.compile("^content :");

    private final RecommendationProvider recommendationProvider;

    public List<ClovaRecommendationResponse> getRecommendationsFromClova(ClovaRecommendationRequest clovaRecommendationRequest) {
        String[] recommendations = recommendationProvider.requestToClovaStudio(clovaRecommendationRequest).split(LINE_SEPARATOR);
        List<ClovaRecommendationResponse> clovaResponses = new ArrayList<>();
        int order = 1;

        for (int i = 0; i < recommendations.length; i++) {
            String line = recommendations[i].trim();

            if (TITLE_PATTERN.matcher(line).matches()) {
                String title = TITLE_PATTERN.matcher(line).replaceFirst("").trim();
                String content = "";

                if (i + 1 < recommendations.length && CONTENT_PATTERN.matcher(recommendations[i + 1].trim()).find()) {
                    content = CONTENT_PATTERN.matcher(recommendations[i + 1].trim()).replaceFirst("").trim();
                    i++;
                }

                clovaResponses.add(new ClovaRecommendationResponse(order, title, content));
                order++;
            }
        }
        return clovaResponses;
    }
}
```
예시 코드입니다
틀린 부분이 있을 수 있는데 참고해주시면 좋을 거 같아요! (해당 [블로그](https://jake-seo-dev.tistory.com/23) 참고해보시면 좋을 거 같습니다.)

2024-10-31 04:38 UTC, HoyeongJeon commented on src/main/java/spring/backend/recommendation/application/GetRecommendationsFromClovaService.java
> +            if (line.matches("^\\d+\\. title :.*")) {
대박...

2024-10-31 09:33 UTC, anxi01 approved these changes
클로바 연동하는게 복잡했을텐데..
고생 많으셨습니다!

2024-10-31 11:05 UTC, merged