Feat: (#58) 빠른 시작 생성 API를 구현한다
KUSITMS-30th-TEAM-C/backend pull request #59
Opened 2024-10-29 14:53 UTC by anxi01

## ✅ PR 유형
어떤 변경 사항이 있었나요?

- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

---

## 📝 작업 내용
- 빠른 시작 생성 API를 구현하였습니다.

### 성공응답
![스크린샷 2024-10-29 오후 11 47 22](https://github.com/user-attachments/assets/376f7774-8a81-4ed1-9e1e-542c355d663f)

### 실패응답 (닉네임 10글자 넘을 경우)
![스크린샷 2024-10-29 오후 11 48 24](https://github.com/user-attachments/assets/a08775e7-2b3c-4e8c-8881-adc7f739babb)

### 실패응답 (숫자 10미만, 300초과일 경우)
![스크린샷 2024-10-29 오후 11 48 43](https://github.com/user-attachments/assets/111148ad-0df0-482c-9428-689fe3c8b9e5)

---

## ✏️ 관련 이슈
- Resolves : #58 

---

## 🎸 기타 사항 or 추가 코멘트
- 아직 완료된 작업은 아닙니다. 기획, 프론트와 요청 값 관련해서 논의해야해서 답변을 기다리고 있습니다.
  - name : 띄어쓰기가 가능한지, 띄어쓰기 포함 10자인지에 대해 답변 대기중입니다.
  - startTime : 오전, 오후를 프론트에서 변환할지, 백에서 변환할지에 대해 답변 대기중입니다.

2024-10-30 04:24 UTC, HoyeongJeon requested changes

2024-10-30 04:24 UTC, HoyeongJeon commented on src/main/java/spring/backend/activity/dto/request/QuickStartRequest.java
> +        Time startTime,
LocalTime이 아닌 Time을 사용하신 이유가 있으신가요?

2024-10-30 04:27 UTC, HoyeongJeon requested changes

2024-10-30 04:27 UTC, HoyeongJeon commented on src/test/java/spring/backend/activity/application/CreateQuickStartServiceTest.java
> +            QuickStartRequest request = new QuickStartRequest(
이 부분이 반복적으로 쓰이면 BeforeEach에 정의해도 좋다고 생각합니다~!

2024-10-30 04:53 UTC, anxi01 commented on src/main/java/spring/backend/activity/dto/request/QuickStartRequest.java
> +        Time startTime,
우선 시작 시간은 시, 분을 이용하는데
LocalTime이 아닌 Time을 사용한 이유는
DB에서 Time 타입으로 저장을 하고 있어서 Time으로 하는게 낫지 않을까 생각했습니다.

근데 LocalTime도 ORM에서 자동으로 Time으로 변경해준다고 해서 LocalTime으로 변경하는 것도 좋아 보입니다

2024-10-30 04:53 UTC, anxi01 commented on src/main/java/spring/backend/activity/dto/request/QuickStartRequest.java
> +        Time startTime,
어떻게 생각하시나요?

2024-10-30 04:57 UTC, anxi01 commented on src/test/java/spring/backend/activity/application/CreateQuickStartServiceTest.java
> +            QuickStartRequest request = new QuickStartRequest(
수정했습니다~ 감사해용

2024-10-30 06:56 UTC, HoyeongJeon requested changes

2024-10-30 06:56 UTC, HoyeongJeon commented on src/main/java/spring/backend/activity/dto/request/QuickStartRequest.java
> +        Time startTime,
java.time 에서 제공해주는 메서드를 쓸 수 있으니까 LocalTime이 더 좋다 생각합니다~!

2024-10-30 15:53 UTC, HoyeongJeon requested changes

2024-10-30 15:53 UTC, HoyeongJeon commented on src/main/java/spring/backend/activity/dto/request/QuickStartRequest.java
> +        Time startTime,
LocalTime을 사용하면 java.time에서 제공하는 유틸을 사용할 수 있으니까 LocalTime을 쓰는게 더 좋아보여요!

2024-10-31 00:47 UTC, HoyeongJeon commented on src/main/java/spring/backend/activity/dto/request/QuickStartRequest.java
> +        Time startTime,
LocalTime이 java.time 패키지에 있으니까 java.time의 더 많은 유틸을 쓸 수 있을거같아 LocalTime이 더 괜찮아보입니다!

2024-10-31 00:48 UTC, HoyeongJeon approved these changes

2024-10-31 00:48 UTC, HoyeongJeon commented
고생했어요~!

2024-10-31 02:02 UTC, anxi01 commented on src/main/java/spring/backend/activity/dto/request/QuickStartRequest.java
> +        Time startTime,
넵! 수정 이슈 파서 작업 진행하도록 하겠습니다!

2024-10-31 02:05 UTC, merged