Feat: (#64) 일반 추천 API를 구현한다.
KUSITMS-30th-TEAM-C/backend pull request #71
Opened 2024-11-01 02:20 UTC by HoyeongJeon

## ✅ PR 유형
어떤 변경 사항이 있었나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

---

## 📝 작업 내용

- 사용자의 활동 선택 API를 구현했습니다.

**요청**

<img width="947" alt="성공 요청" src="https://github.com/user-attachments/assets/0de5812e-41cd-4da4-a737-2f8ea6e43185">

**성공 응답**

<img width="940" alt="성공 응답" src="https://github.com/user-attachments/assets/94d86695-deee-4af9-b7a7-249cd121eb00">

** 실패 응답**

<img width="690" alt="실패 응답" src="https://github.com/user-attachments/assets/d8d5f216-3ce4-44be-ac3a-dccc6740c851">

---

## ✏️ 관련 이슈
- Resolves : #64 

---

## 🎸 기타 사항 or 추가 코멘트
- Member , Guest ArgumentResolver 생성한 코드를 보았습니다. 추후 추가할 예정이라 Member 검증 로직을 service에서 삭제했습니다. 
- GetRecommendationFromClovaController에 Authoriztion 헤더를 추가했습니다. 이 부분도 @AuthorziedMember 어노테이션을 적용해야하지만 개발 도중엔 테스트의 편리함을 위해 아직 붙이지 않았습니다. 서로 인지하고 있으면 될 거 같아요.

2024-11-01 15:08 UTC, HoyeongJeon commented
![image](https://github.com/user-attachments/assets/cc2cd51e-9855-41f0-a1e3-33a8253f7476)

![image](https://github.com/user-attachments/assets/b7821708-5116-485d-a9d0-edb4f59cdc41)

키워드는 한 개만 저장되도록 수정했습니다.

2024-11-01 17:52 UTC, anxi01 commented on src/main/java/spring/backend/activity/application/UserActivitySelectService.java
> +        Activity activity = Activity.create(member.getId(), null , userActivitySelectRequest.spareTime(), userActivitySelectRequest.type(), userActivitySelectRequest.keyword(), userActivitySelectRequ
null 부분 공백 확인해주세요!

2024-11-01 17:56 UTC, anxi01 commented on src/main/java/spring/backend/activity/domain/entity/Activity.java
> +                .finished(false)
활동은 생성하게되면 매번 finished는 false이니

```java
@Builder.Default
    private Boolean finished = false; 
```
이렇게 Builder의 default값으로 false로 설정하는건 어떨까요?

그렇게 되면 create 메소드에서 `finished(false)` 를 설정안해줘도 자동으로 false로 생성돼요!

2024-11-01 18:00 UTC, anxi01 commented on src/main/java/spring/backend/activity/dto/request/UserActivitySelectRequest.java
> +        @NotNull(message = "Content는 필수 입력 항목입니다.")
위에서 전부 한글로 통일성있게 message를 설정해주고 있는데 `Content`보다 `내용`이 어떨까요?

2024-11-01 18:03 UTC, anxi01 commented on src/main/java/spring/backend/activity/exception/ActivityErrorCode.java
> +    NOT_A_MEMBER(HttpStatus.FORBIDDEN, "사용자가 멤버 사용자가 아닙니다.");
`@AuthorizedMember`를 적용하면 `NOT_A_MEMBER(HttpStatus.FORBIDDEN, "사용자가 멤버 사용자가 아닙니다.");`
에러코드는 제거해도 될 거 같습니다

2024-11-01 18:06 UTC, anxi01 commented on src/main/java/spring/backend/activity/presentation/UserActivitySelectController.java
> +    public ResponseEntity<RestResponse<Long>> userActivitySelection(@LoginMember Member member, @Valid @RequestBody UserActivitySelectRequest userActivitySelectRequest) {
`UserActivitySelectController` 도 직관적이라서 좋은 거 같아요!

저는 현재 URI가 `/v1/user-activity-selection` 이렇게 되어 있는데, 지금 현재 API에서의 행위는
일반 추천 활동을 저장하는 것이기 때문에 `/v1/activities` 로 하면 RESTful한 API를 만들 수 있을 거 같아요!

2024-11-01 18:07 UTC, anxi01 commented on src/main/java/spring/backend/activity/presentation/swagger/UserActivitySelectSwagger.java
> +@Tag(name = "UserActivitySelection", description = "활동 선택")
[화상 논의]
- 스웨거 작성 시, @Tag를 작성할 때 도메인명을 name으로 지정하기!

2024-11-01 18:08 UTC, anxi01 commented on src/main/java/spring/backend/activity/presentation/swagger/UserActivitySelectSwagger.java
> +    ResponseEntity<RestResponse<Long>>  userActivitySelection(@Parameter(hidden = true) Member member, UserActivitySelectRequest userActivitySelectRequest);
`<RestResponse<Long>>  userActivitySelection` 사이에 공백 2개 존재합니다!

2024-11-01 18:14 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/application/GetRecommendationsFromClovaService.java
> +                return null;
q) 만약 keywordText가 case에 존재하지 않을 경우, null이 반환되는데 응답에도 단순 null을 반환하나요?
null 처리에 관해서 고려해봐야할 거 같아요

2024-11-01 18:25 UTC, anxi01 requested changes
고생하셨습니다!

게더에서 얘기했던 부분 수정 부탁드리고, 아래 리뷰도 참고해주시면 좋을 거 같아요!

2024-11-01 18:25 UTC, anxi01 commented on src/main/java/spring/backend/activity/application/UserActivitySelectService.java
> +        Activity activity = Activity.create(member.getId(), null , userActivitySelectRequest.spareTime(), userActivitySelectRequest.type(), userActivitySelectRequest.keyword(), userActivitySelectRequ
null 부분 공백 확인해주세요!

2024-11-01 18:25 UTC, anxi01 commented on src/main/java/spring/backend/activity/domain/entity/Activity.java
> +                .finished(false)
활동은 생성하게되면 매번 finished는 false이니

```java
@Builder.Default
    private Boolean finished = false; 
```
이렇게 Builder의 default값으로 false로 설정하는건 어떨까요?

그렇게 되면 create 메소드에서 `finished(false)` 를 설정안해줘도 자동으로 false로 생성돼요!

2024-11-01 18:25 UTC, anxi01 commented on src/main/java/spring/backend/activity/dto/request/UserActivitySelectRequest.java
> +        @NotNull(message = "Content는 필수 입력 항목입니다.")
위에서 전부 한글로 통일성있게 message를 설정해주고 있는데 `Content`보다 `내용`이 어떨까요?

2024-11-01 18:25 UTC, anxi01 commented on src/main/java/spring/backend/activity/exception/ActivityErrorCode.java
> +    NOT_A_MEMBER(HttpStatus.FORBIDDEN, "사용자가 멤버 사용자가 아닙니다.");
`@AuthorizedMember`를 적용하면 `NOT_A_MEMBER(HttpStatus.FORBIDDEN, "사용자가 멤버 사용자가 아닙니다.");`
에러코드는 제거해도 될 거 같습니다!

2024-11-01 18:25 UTC, anxi01 commented on src/main/java/spring/backend/activity/presentation/UserActivitySelectController.java
> +    public ResponseEntity<RestResponse<Long>> userActivitySelection(@LoginMember Member member, @Valid @RequestBody UserActivitySelectRequest userActivitySelectRequest) {
`UserActivitySelectController` 도 직관적이라서 좋은 거 같아요!

저는 현재 URI가 `/v1/user-activity-selection` 이렇게 되어 있는데, 지금 현재 API에서의 행위는
일반 추천 활동을 저장하는 것이기 때문에 `/v1/activities` 로 하면 RESTful한 API를 만들 수 있을 거 같아요!

2024-11-01 18:25 UTC, anxi01 commented on src/main/java/spring/backend/activity/presentation/swagger/UserActivitySelectSwagger.java
> +@Tag(name = "UserActivitySelection", description = "활동 선택")
[화상 논의]
- 스웨거 작성 시, @Tag를 작성할 때 도메인명을 name으로 지정하기!

2024-11-01 18:25 UTC, anxi01 commented on src/main/java/spring/backend/activity/presentation/swagger/UserActivitySelectSwagger.java
> +    ResponseEntity<RestResponse<Long>>  userActivitySelection(@Parameter(hidden = true) Member member, UserActivitySelectRequest userActivitySelectRequest);
`<RestResponse<Long>>  userActivitySelection` 사이에 공백 2개 존재합니다!

2024-11-01 18:25 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/application/GetRecommendationsFromClovaService.java
> +        switch (keywordText.toLowerCase()) {
q) 한글 텍스트인데 `LowerCase` 메소드를 사용한 이유가 궁금합니다

2024-11-01 18:25 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/application/GetRecommendationsFromClovaService.java
> +                return null;
q) 만약 keywordText가 case에 존재하지 않을 경우, null이 반환되는데 응답에도 단순 null을 반환하나요?
null 처리에 관해서 고려해봐야할 거 같아요

2024-11-01 18:25 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/application/GetRecommendationsFromClovaService.java
> +        switch (keywordText.toLowerCase()) {
```java
    return switch (keywordText.toLowerCase()) {
            case "자기개발" -> Keyword.Category.SELF_DEVELOPMENT;
            case "건강" -> Keyword.Category.HEALTH;
            case "자연" -> Keyword.Category.NATURE;
            case "문화/예술" -> Keyword.Category.CULTURE_ART;
            case "엔터테인먼트" -> Keyword.Category.ENTERTAINMENT;
            case "휴식" -> Keyword.Category.RELAXATION;
            case "소셜" -> Keyword.Category.SOCIAL;
            default -> null;
        };
```
향상된 스위치문 사용해서 return 중복 없이 바로 반환해도 깔끔할 거 같아요

2024-11-01 18:25 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/infrastructure/clova/dto/request/ClovaStudioPrompt.java
> +}
프롬프트 작성하시느라 고생 많으셨습니다ㅜㅜ

2024-11-03 04:33 UTC, HoyeongJeon commented on src/main/java/spring/backend/activity/domain/entity/Activity.java
> +                .finished(false)
와 몰랐는데~! 감사합니다.

2024-11-03 04:35 UTC, HoyeongJeon commented on src/main/java/spring/backend/activity/dto/request/UserActivitySelectRequest.java
> +        @NotNull(message = "Content는 필수 입력 항목입니다.")
수정하겠습니다~!

2024-11-03 04:37 UTC, HoyeongJeon commented on src/main/java/spring/backend/activity/presentation/swagger/UserActivitySelectSwagger.java
> +    ResponseEntity<RestResponse<Long>>  userActivitySelection(@Parameter(hidden = true) Member member, UserActivitySelectRequest userActivitySelectRequest);
수정했습니다~!

2024-11-03 05:08 UTC, HoyeongJeon commented on src/main/java/spring/backend/recommendation/application/GetRecommendationsFromClovaService.java
> +        switch (keywordText.toLowerCase()) {
아 처음엔 keyword를 영어로 응답을 받았어서, toLowerCase로 클로바 스튜디오의 응답값을 통일시켜주려 했습니다. 
지금은 keyword가 한국어인데 이 부분을 신경쓰지 못하고 안바꿔놨네요 
감사합니다 ㅎㅎ

2024-11-03 05:12 UTC, HoyeongJeon commented on src/main/java/spring/backend/recommendation/application/GetRecommendationsFromClovaService.java
> +                return null;
음... 이런 경우 "기타"로 변경을 할까요 ? 
고민이 되는 부분이네요..
1. "기타"로 처리
- Keyword에 기타 추가
2. 에러로 처리 
- 응답이 제대로 온 것이 맞는데 , 키워드가 없는 값이라고 에러라 처리하는 것이 맞을까?
3. 사용자의 요청 키워드 중 첫번째 값을 null 대신 추가.

일단 이렇게 생각이 드는데 어떨까요?
더 좋은 아이디어 있으시면 알려주세요.

2024-11-03 05:13 UTC, HoyeongJeon commented on src/main/java/spring/backend/activity/presentation/UserActivitySelectController.java
> +    public ResponseEntity<RestResponse<Long>> userActivitySelection(@LoginMember Member member, @Valid @RequestBody UserActivitySelectRequest userActivitySelectRequest) {
수정하겠습니다~!

2024-11-03 10:21 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/application/GetRecommendationsFromClovaService.java
> +                return null;
이 부분은 개발에서 결정하면 안될 거 같고 기획이랑 논의가 필요해 보입니다!

2024-11-04 13:51 UTC, anxi01 commented on src/main/java/spring/backend/activity/presentation/swagger/UserActivitySelectSwagger.java
> +            operationId = "/v1/user-activity-selection"
"/v1/activities" 변경되어야할 거 같아요!

2024-11-04 15:02 UTC, HoyeongJeon commented on src/main/java/spring/backend/activity/presentation/swagger/UserActivitySelectSwagger.java
> +            operationId = "/v1/user-activity-selection"
헉 안바꿨네여 
감사합니다~

2024-11-07 16:42 UTC, HoyeongJeon commented
<img width="1387" alt="image" src="https://github.com/user-attachments/assets/cb2c412f-2a2e-4036-80eb-97fc062e55bf">

추천 활동의 키워드가 올바르지 않은 경우 한번 더 재시도를 하고 그래도 키워드가 올바르지 않으면 에러를 반환합니다.

2024-11-07 16:43 UTC, HoyeongJeon commented on src/main/java/spring/backend/recommendation/application/GetRecommendationsFromClovaService.java
> +                return null;
[논의 사항]
- 1회 재시도
- 재시도 후 키워드가 올바르지 않은 경우 예외 반환

2024-11-08 09:39 UTC, anxi01 commented on src/main/java/spring/backend/activity/presentation/UserActivitySelectController.java
> +    }
반환 타입과 반환 값이 미스 잘못된 거 같아요

2024-11-08 10:44 UTC, HoyeongJeon commented on src/main/java/spring/backend/activity/presentation/UserActivitySelectController.java
> +    }
헉 고칠게여

2024-11-08 10:44 UTC, HoyeongJeon commented on src/main/java/spring/backend/activity/presentation/UserActivitySelectController.java
> +    }
이름을 이상하게 썼네

2024-11-08 17:55 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/application/GetRecommendationsFromClovaService.java
> +                        || clovaResponse.getKeywordCategory().toString().isEmpty()
q) Category의 toString()으로 비교하는 이유가 있을까요?
만약 toString() 을 오버라이드해서 사용하지 않다면 Enum의 name() 메소드를 이용하는게 더 낫지 않을까 싶어요!

2024-11-08 18:03 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/application/GetRecommendationsFromClovaService.java
> +        if (clovaRecommendationRequest.activityType().equals(Type.ONLINE) && Arrays.toString(clovaRecommendationRequest.keywords()).contains("NATURE")) {
`Arrays.toString(clovaRecommendationRequest.keywords()).contains("NATURE")`
위 메소드는 문자열 기반으로 검색을 진행하고 있는데

만약 NATURE가 request.keywords()에 포함되어있는 여부를 찾는 거라면
`Arrays.asList(categories).contains(Category.NATURE)`
위와 같이 Enum의 값을 사용하는 것이 타입 안정성이 있을 거 같습니다

2024-11-09 06:53 UTC, HoyeongJeon commented on src/main/java/spring/backend/recommendation/application/GetRecommendationsFromClovaService.java
> +                        || clovaResponse.getKeywordCategory().toString().isEmpty()
name 메서드를 몰랐어요..!

2024-11-09 07:12 UTC, HoyeongJeon commented on src/main/java/spring/backend/recommendation/application/GetRecommendationsFromClovaService.java
> +                        || clovaResponse.getKeywordCategory().toString().isEmpty()
```Java
package lang.string.equals;

public class StringEqualsMain3 {
    public static void main(String[] args) {
        String str1 = new String("hello");
        String str2 = new String("hello");
        String str3 = null;
        String str4 = null;
        System.out.println("new String() == 비교: " + (str1 == str2)); // false
        System.out.println("new String() equals 비교: " + (str1.equals(str2))); // true
        System.out.println("null == " + (str3 == str4)); // true 
        System.out.println("null equals 비교: " + (str3.equals(str4))); // NPE
    }
}
```

`String` 클래스 비교할 때는 `==` 비교가 아니라 항상 `equals()` 비교를 해야한다. 
**동일성(Identity)**: `==` 연산자를 사용해서 두 객체의 참조가 동일한 객체를 가리키고 있는지 확인
 **동등성(Equality)**: `equals()` 메서드를 사용하여 두 객체가 논리적으로 같은지 확인

NULL값에 대한 안전한 비교

```Java
import java.util.Objects;

System.out.println("null safe equals: " + Objects.equals(str3, str4));
```

2024-11-09 07:30 UTC, HoyeongJeon commented
> q) Category의 toString()으로 비교하는 이유가 있을까요?
만약 toString() 을 오버라이드해서 사용하지 않다면 Enum의 name() 메소드를 이용하는게 더 낫지 않을까 싶어요!

이 부분의 로직이 

```Java
private boolean containsInvalidKeyword(List<ClovaRecommendationResponse> clovaResponses) {
        return clovaResponses.stream().anyMatch(clovaResponse ->
                clovaResponse.getKeywordCategory() == null
                        || !isValidKeywordCategory(clovaResponse.getKeywordCategory()));
    }
```

인데 clovaResponse.getKeywordCategory() 가 null이 아닌 상황에서 name() 이나 toString()이 빈값을 반환할 가능성이 없다고 생각해서 지웠습니다~!
name() 메서드는 ENUM 상수의 이름을 문자열로 반환하니까 빈 값을 반환할리 없다고 판단했어요

2024-11-09 15:54 UTC, anxi01 commented
> > q) Category의 toString()으로 비교하는 이유가 있을까요?
> > 만약 toString() 을 오버라이드해서 사용하지 않다면 Enum의 name() 메소드를 이용하는게 더 낫지 않을까 싶어요!
> 
> 이 부분의 로직이
> 
> ```java
> private boolean containsInvalidKeyword(List<ClovaRecommendationResponse> clovaResponses) {
>         return clovaResponses.stream().anyMatch(clovaResponse ->
>                 clovaResponse.getKeywordCategory() == null
>                         || !isValidKeywordCategory(clovaResponse.getKeywordCategory()));
>     }
> ```
> 
> 인데 clovaResponse.getKeywordCategory() 가 null이 아닌 상황에서 name() 이나 toString()이 빈값을 반환할 가능성이 없다고 생각해서 지웠습니다~! name() 메서드는 ENUM 상수의 이름을 문자열로 반환하니까 빈 값을 반환할리 없다고 판단했어요

clovaResponse.getKeywordCategory() 가 null이 아닌 상황에서 name() 이나 toString()이 빈값을 반환할 가능성
-> *null인 상황에서 말씀하시는 거죠?

2024-11-09 15:54 UTC, anxi01 approved these changes
고생하셨습니다~

2024-11-09 15:58 UTC, HoyeongJeon commented
> *null인 상황에서 말씀하시는 거죠?
네~!

2024-11-09 16:02 UTC, merged