Feat: (#65) 빠른시작 추천 API를 구현한다.
KUSITMS-30th-TEAM-C/backend pull request #75
Opened 2024-11-03 13:51 UTC by HoyeongJeon

## ✅ PR 유형
어떤 변경 사항이 있었나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

---

## 📝 작업 내용

- 빠른 시작으로 추천활동을 선택한 경우 API를 구현했습니다.

### 성공응답

![image](https://github.com/user-attachments/assets/4e92f8f4-d334-4043-9f6c-a8e1dc73c819)

### 실패
** 빠른시작이 없는 경우 **

![image](https://github.com/user-attachments/assets/b2322a03-d213-46db-9bb5-a673ca38056d)

---

## ✏️ 관련 이슈

- Resolves : #65 

---

## 🎸 기타 사항 or 추가 코멘트

2024-11-06 05:55 UTC, anxi01 requested changes
고생하셨습니다!

2024-11-06 05:55 UTC, anxi01 commented on src/main/java/spring/backend/activity/presentation/swagger/QuickStartActivitySelectSwagger.java
> +    ResponseEntity<RestResponse<Long>> quickStartUserActivitySelect(@Parameter(hidden = true) Member member, @PathVariable Long quickStartId, QuickStartActivitySelectRequest quickStartActivitySelectR
@PathVariable 어노테이션 중복됩니다

2024-11-06 05:55 UTC, anxi01 commented on src/test/java/spring/backend/activity/application/QuickStartActivitySelectServiceTest.java
> +//    @DisplayName("유효한 활동 선택인 경우 저장된 ID를 반환한다")
테스트 주석처리하신 이유가 있을까요? 만약 사용하지 않는 테스트라면 제거해도 좋을 거 같습니다!

2024-11-07 05:21 UTC, HoyeongJeon commented on src/test/java/spring/backend/activity/application/QuickStartActivitySelectServiceTest.java
> +//    @DisplayName("유효한 활동 선택인 경우 저장된 ID를 반환한다")
헐 바로 지울게여

2024-11-08 18:14 UTC, anxi01 commented on src/main/java/spring/backend/activity/dto/request/QuickStartActivitySelectRequest.java
> +public record QuickStartActivitySelectRequest(
request, response를 앞으로 기능마다 만들까봐요!
지금 위에서 만든 것처럼 `기능명 + Request/Response`으로 만드는거 좋은 거 같아요!

사실 DTO가 중복되는 필드도 많아서 중복이 많으면 하나의 DTO를 사용하려 했는데
이렇게 하다 보니 나중에 DTO 타입 변경이나 필드 추가, 제거 등 진행할 때 관련된 모든 부분(테스트 코드, 이외 등등)을 변경하는데
잘못하면 빠뜨릴 수 있겠더라고요..!

앞으로 이처럼 신규 기능 만들면 DTO가 다른 DTO랑 중복되더라도 신규로 추가하는 건 어떨까요?

2024-11-08 18:16 UTC, anxi01 approved these changes
고생하셨습니다!
#71 일반 추천 API 머지되고 이 PR 머지하는 걸로 해요!

2024-11-09 16:10 UTC, merged