Chore: (80) Naver API 맵을 연동한다.
KUSITMS-30th-TEAM-C/backend pull request #82
Opened 2024-11-09 16:20 UTC by HoyeongJeon

## ✅ PR 유형
어떤 변경 사항이 있었나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

---

## 📝 작업 내용

- 네이버 맵 API를 서비스와 연동했습니다.

![스크린샷 2024-11-10 00 41 45](https://github.com/user-attachments/assets/0b9fb907-f079-4db5-bfde-9fe570c57631)

---

## ✏️ 관련 이슈

- Resolves : #80 

---

## 🎸 기타 사항 or 추가 코멘트

- 현재 연동만 한 상황입니다. 값을 뽑아내고, 좌표를 전달하거나 지도 url을 만드는 작업은 다른 이슈를 파서 진행할 예정입니다.

2024-11-09 21:01 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/infrastructure/map/naver/application/NaverMapService.java
> +    public void search(String query) {
q) dto가 없는데 응답은 어떻게 되는건가요?

2024-11-09 21:04 UTC, anxi01 commented
q) 참고한 블로그가 있을까요?? 참고한 블로그 남겨주시면 좋을 거 같아요

2024-11-10 00:58 UTC, HoyeongJeon commented on src/main/java/spring/backend/recommendation/infrastructure/map/naver/application/NaverMapService.java
> +    public void search(String query) {
현재 응답은 사진처럼 오는데요, 해당 응답값을 처리하고 필요한 좌표값을 뽑아내는 작업은 다른 이슈를 파서 할 생각입니다~!

2024-11-10 00:58 UTC, HoyeongJeon commented
> q) 참고한 블로그가 있을까요?? 참고한 블로그 남겨주시면 좋을 거 같아요

https://developers.naver.com/docs/serviceapi/search/local/local.md

https://developers.naver.com/docs/serviceapi/search/blog/blog.md#%EA%B2%80%EC%83%89-api-%EB%B8%94%EB%A1%9C%EA%B7%B8-%EA%B2%80%EC%83%89-%EA%B5%AC%ED%98%84-%EC%98%88%EC%A0%9C

위 두 글을 토대로 작성했습니다!

2024-11-10 01:00 UTC, HoyeongJeon commented on src/main/java/spring/backend/recommendation/infrastructure/map/naver/application/NaverMapService.java
> +    public void search(String query) {
사진에 짤려있는데, 응답에 주소와 좌표값까지 같이 옵니다.

2024-11-10 07:48 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/infrastructure/map/naver/application/NaverMapService.java
> +public class NaverMapService implements MapService {
DIP 고수... 멋져요

2024-11-10 07:50 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/infrastructure/map/naver/application/NaverMapService.java
> +    private String fetchResponse(String apiUrl, Map<String, String> requestHeaders) {
docs에서 제공하는 대로 코드 짜는 것도 너무 좋은데
형도 WebClient 썼었으니까 WebClient를 써서 구현하는건 어떻게 생각하시나요??

2024-11-11 05:12 UTC, HoyeongJeon commented on src/main/java/spring/backend/recommendation/infrastructure/map/naver/application/NaverMapService.java
> +    private String fetchResponse(String apiUrl, Map<String, String> requestHeaders) {
WebClient로 요청을 보내면 검색 결과가 없게 와서... 
내가 잘못짠거겠지만 결과를 못받아와서 docs 방식으로 짰어요 🥲

2024-11-11 05:19 UTC, HoyeongJeon commented on src/main/java/spring/backend/recommendation/infrastructure/map/naver/application/NaverMapService.java
> +    private String fetchResponse(String apiUrl, Map<String, String> requestHeaders) {
WebClient로 작성하면 계속 응답결과가 없다고 와서.. 
내가 잘못짠거겠지만 일단 docs를 바탕으로 짰습니다..🥲

2024-11-11 10:14 UTC, anxi01 requested changes
Service에 대해 좀 더 고민해보면 좋을 거 같습니다!
저도 좀 더 찾아봐야할 거 같네요..

2024-11-11 10:14 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/infrastructure/map/naver/application/NaverMapService.java
> +public class NaverMapService implements MapService {
![스크린샷 2024-11-11 오후 6 58 01](https://github.com/user-attachments/assets/e0ab8481-3874-47c5-b1b3-29d1725bec94)

저번에 준영님이 남겨주신 리뷰인데 Service 대신 다른 이름을 고려해봐도 좋을 거 같습니다.
어노테이션도 그 성격에 맞춰 변경하면 좋을 거 같아요!

> Component 는 di 를 위한 기본 annotation 입니다.
@Service, @Controller, @Repository 등은 @Component를 상속 받고 있습니다.
@Service 는 @Component 와 기능상의 차이는 없습니다.
하지만 비즈니스 레이어를 구분하기 위해 사용된다고 보시면 됩니다.
@Component 는 원형, 즉 기능을 수행하는 라이브러리 성격에 붙여 주시면 될거같고,
@Service 는 비즈니스 로직을 구현하는 객체에 사용하면 될거같습니다. 

[출처](https://okky.kr/questions/1041492)

2024-11-11 10:14 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/infrastructure/map/naver/application/NaverMapService.java
> +    private final ObjectMapper objectMapper = new ObjectMapper();
Spring Boot에서는 기본적으로 `ObjectMapper`를 빈으로 자동으로 설정해주기 때문에

```java
@RequiredArgsConstructor
...

private final ObjectMapper objectMapper; 
```
로 DI해주는게 더 깔끔해 보입니다.

2024-11-11 15:08 UTC, HoyeongJeon commented on src/main/java/spring/backend/recommendation/infrastructure/map/naver/application/NaverMapService.java
> +    private final ObjectMapper objectMapper = new ObjectMapper();
헐~ 몰랐어여 
수정할게요~

2024-11-11 15:29 UTC, HoyeongJeon commented on src/main/java/spring/backend/recommendation/infrastructure/map/naver/application/NaverMapService.java
> +public class NaverMapService implements MapService {
`PlaceInfoProvider` 어떤가요!?

2024-11-12 15:16 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/infrastructure/map/naver/application/NaverMapService.java
> +public class NaverMapService implements MapService {
좋아요~!

2024-11-12 15:17 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/infrastructure/map/naver/application/NaverMapService.java
> +    private final ObjectMapper objectMapper = new ObjectMapper();
기존 코드인
```private final ObjectMapper objectMapper = new ObjectMapper();```

이것도 괜찮은 거 같긴 해요!
근데 DI를 하면 더 좋지 않을까 싶었습니다~

2024-11-13 00:08 UTC, anxi01 requested changes
이전 커밋 내역 존재해서 git pull, rebase해서 최신화 하고 다시 push 해주세요!

2024-11-13 01:35 UTC, HoyeongJeon commented
> 이전 커밋 내역 존재해서 git pull, rebase해서 최신화 하고 다시 push 해주세요!

2024-11-13 05:14 UTC, anxi01 approved these changes
고생하셨습니다!

2024-11-13 08:48 UTC, merged