Fix: (#91) AI 추천시 사용되는 Message Request DTO와 RecommendationProvider를 리팩토링한다.
KUSITMS-30th-TEAM-C/backend pull request #92
Opened 2024-11-13 16:28 UTC by HoyeongJeon

## ✅ PR 유형
어떤 변경 사항이 있었나요?

- [x] 새로운 기능 추가
- [ ] 버그 수정
- [x] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [x] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [x] 파일 혹은 폴더명 수정
- [x] 파일 혹은 폴더 삭제

---

## 📝 작업 내용

- Message를 범용적으로 사용할 수 있도록 리팩토링했습니다.
- DIP를 적용하기 위해 RecommendationProvider와 Clova 의 결합을 분리했습니다.

---

## ✏️ 관련 이슈

- Resolves : #91 

---

## 🎸 기타 사항 or 추가 코멘트

2024-11-13 18:53 UTC, anxi01 requested changes
게더에서 페어프로그래밍이랄까? ㅋㅋㅋ 재밌었습니당
리뷰 보시고 수정해주시면 좋을 거 같습니다!

참고로 지금 한 클래스 내에서 `AIRecommendationRequest` 의 변수명이 여러가지라서 
만약 Clova를 사용하는 곳이면 clova~~~ 로 명시적으로 네이밍하는게 더 좋을 거 같기도 해요!

형꺼 머지되면 #81 OpenAPI 연동 작업 진행할게요~~!

2024-11-13 18:53 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/application/GetRecommendationsFromClovaService.java
> +
불필요한 개행같아요!

2024-11-13 18:53 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/infrastructure/clova/application/ClovaRecommendationProvider.java
> +//        if (result == null || result.getResult() == null || result.getResult().getMessage() == null || result.getResult().getMessage().getContent() == null) {
`src/main/java/spring/backend/recommendation/application/GetRecommendationsFromClovaService.java` 에서 사용되고 있어서 불필요한 주석 같습니다

2024-11-13 18:53 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/dto/request/AIRecommendationRequest.java
> +@Log4j2
원래 dto에서 검증 로직 추가했을 때 로깅했던 거 같은데 
지금은 검증로직 빠졌으니 사용 안하면 제거해도 좋을 거 같습니다

2024-11-13 18:53 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/dto/request/AIRecommendationRequest.java
> +                                      @Schema(description = "위치(activityType이 OFFLINE, ONLINE_AND_OFFLINE인 경우에만 필요합니다.)", example = "서울시 강남구")
지금 코드의 들여쓰기가 통일되지 않고 있는데 이 부분 확인 부탁드립니다.

```java
public record ClovaRecommendationRequest(
    @NotNull(message = "자투리 시간은 필수 입력 항목입니다.")
    @Min(value = 10, message = "자투리 시간은 10부터 300 사이의 숫자로 입력해주세요.")
    @Max(value = 300, message = "자투리 시간은 10부터 300 사이의 숫자로 입력해주세요.")
    @Schema(description = "자투리 시간", example = "30")
    Integer spareTime,

    @NotNull(message = "활동 유형은 필수 입력 항목입니다.")
    @Schema(description = "활동 타입(ONLINE, OFFLINE, ONLINE_AND_OFFLINE 중 하나를 선택합니다.)", example = "OFFLINE")
    Type activityType,

    @NotNull(message = "키워드는 필수 입력 항목입니다.")
    @Schema(description = "활동 키워드", example = "[\"NATURE\",\"CULTURE_ART\"]")
    Keyword.Category[] keywords,

    @Schema(description = "위치(activityType이 OFFLINE, ONLINE_AND_OFFLINE인 경우에만 필요합니다.)", example = "서울시 강남구")
    String location
) {
}
```
이런 형식이면 더 깔끔할 거 같아요

2024-11-13 18:53 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/infrastructure/clova/application/ClovaRecommendationProvider.java
> +    private final WebClient clovaStudioWebClient;
core의 `private final WebClient clovaStudioWebClient;`를 주입받아 사용하고 있는데
core는 여러 도메인에서 공용적으로 사용되는 패키지라 주입받지 않고(`src/main/java/spring/backend/core/configuration/webclient/WebClientConfiguration.java` 제거)

```java
WebClient.create()
         .post()
          ...
```
로 바로 생성해서 사용하는게 인프라 단에서 불필요한 의존 없이 구현할 수 있을 거 같아요!

2024-11-13 18:53 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/infrastructure/clova/application/ClovaService.java
> +    public ClovaResponse requestToClovaStudio(AIRecommendationRequest aiRecommendationRequest) {
`ClovaRecommendationProvider`로 기능 이관돼서 이 클래스는 제거해주세요!

2024-11-13 18:53 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/infrastructure/dto/Message.java
> +        if (isActivityTypeOfflineOrOnlineAndOffline(activityType, location)) {
분기 처리에 따른 책임을 분리할 수 있는 코드!!! 너무 좋아요!

2024-11-14 04:01 UTC, HoyeongJeon commented
너무 급하게 올리느라 꼼꼼히 확인하지 못하고 올렸네요 😓
자세히 봐주셔서 감사합니다~!

2024-11-14 04:16 UTC, HoyeongJeon commented
요청 
<img width="1386" alt="image" src="https://github.com/user-attachments/assets/30920e8e-7cc9-46db-a67c-7dfb9be730f6">

응답
<img width="1063" alt="image" src="https://github.com/user-attachments/assets/89e2f523-a56e-4970-9c04-ee9de756a242">

2024-11-14 11:00 UTC, HoyeongJeon commented
```Java
package spring.backend.recommendation.presentation;

@RestController
@RequiredArgsConstructor
@RequestMapping("/v1/recommendations")
public class GetRecommendationsFromClovaController implements GetRecommendationsFromClovaSwagger {
    private final GetRecommendationsFromClovaService getRecommendationsFromClovaService;

    @Authorization
    @PostMapping
    public ResponseEntity<RestResponse<List<ClovaRecommendationResponse>>> requestRecommendations(@AuthorizedMember Member member, @Valid @RequestBody AIRecommendationRequest aiRecommendationRequest) {
        List<ClovaRecommendationResponse> response = getRecommendationsFromClovaService.getRecommendationsFromClova(aiRecommendationRequest);
        return ResponseEntity.ok(new RestResponse<>(response));
    }
}
```

해당 코드가 현재 clova에 종속적입니다. 
사용자의 추천 요청을 받는 API를 하나로 만들면 좋을거같은데, 그러려면 
Response의 형태가 같아야할거 같아요.

OpenAI의 Response 형태도 같다면 컨트롤러의 이름을 변경하고 API 하나로만 추천 요청을 받으면 깔끔할거 같습니다.

그게 아니라면 요청을 두개로 나눠도 좋다 생각하는데 편하게 생각 말해주세요~!

2024-11-14 18:36 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/infrastructure/clova/application/ClovaRecommendationProvider.java
> +            WebClient webClient = WebClient.builder()
q) builder()로 하시는 이유가 있을까요?

WebClient.create()를 통해서 headers로 동일한 헤더 설정을 할 수 있긴 한데
특정 이유가 있는지 궁금합니다

2024-11-14 18:57 UTC, anxi01 commented
> ```java
> package spring.backend.recommendation.presentation;
> 
> @RestController
> @RequiredArgsConstructor
> @RequestMapping("/v1/recommendations")
> public class GetRecommendationsFromClovaController implements GetRecommendationsFromClovaSwagger {
>     private final GetRecommendationsFromClovaService getRecommendationsFromClovaService;
> 
>     @Authorization
>     @PostMapping
>     public ResponseEntity<RestResponse<List<ClovaRecommendationResponse>>> requestRecommendations(@AuthorizedMember Member member, @Valid @RequestBody AIRecommendationRequest aiRecommendationRequest) {
>         List<ClovaRecommendationResponse> response = getRecommendationsFromClovaService.getRecommendationsFromClova(aiRecommendationRequest);
>         return ResponseEntity.ok(new RestResponse<>(response));
>     }
> }
> ```
> 
> 해당 코드가 현재 clova에 종속적입니다. 사용자의 추천 요청을 받는 API를 하나로 만들면 좋을거같은데, 그러려면 Response의 형태가 같아야할거 같아요.
> 
> OpenAI의 Response 형태도 같다면 컨트롤러의 이름을 변경하고 API 하나로만 추천 요청을 받으면 깔끔할거 같습니다.
> 
> 그게 아니라면 요청을 두개로 나눠도 좋다 생각하는데 편하게 생각 말해주세요~!

말씀하시려는 의도가 현재 OAuth 로그인 과정처럼 런타임 시점에서 Clova, OpenAI를 지정해서 다형성을 통해 하나의 추상화된 인터페이스에 의존하도록 만들어 특정 구현체에 의존하지 않는게 좋겠다고 하시는 거라면 좋은 생각 같습니다! (사실 난 너무 좋아요.. 대단쓰)

그런데 코드가 특정 기술에 종속적이면 안좋은걸까요?
클로바는 저희 서비스의 핵심 AI 서비스라 변경될 일이 없고 계속해서 사용될거라 생각하는데 서비스에서 명시적으로 `클로바 추천을 얻어오는 기능`을 담당하고 있는데 이거를 추상화해버리면 어디서 추천을 해오는지 쉽게 확인할 수 있을까요?
위 질문은 단순 저만의 고민입니다 ㅋㅋㅋ 
종속을 피하고 추상화를 하는게 과연 옳을까? 라는 생각이 들었어서 저 자신에게 질문을 했던 거라 너무 깊게 고민 안하셔도 될 거 같아요!

우선 추상화해서 작업을 하는건 너무 좋을 거 같은데
이번 스프린트도 얼마 남지 않았고(할 작업이 생각보다 많음..) 이 작업을 토대로 OpenAI도 변경해야해서 
위 내용은 슬랙에 적어두고 추후 기능 구현 다하고 리팩토링하거나 중간에 시간 될 때 변경하면 좋을 거 같습니다!

근데 이건 제 생각이라 호영이형의 생각을 말해주시면 그걸로 결정하면 될 거 같아요~

2024-11-15 00:50 UTC, HoyeongJeon commented on src/main/java/spring/backend/recommendation/infrastructure/clova/application/ClovaRecommendationProvider.java
> +            WebClient webClient = WebClient.builder()
이유는 딱히 없고 ㅎ... 
그냥 WebClientConfiguration을 삭제하면서 긁어왔어요 ㅎ;
builder가 별로인가요? 
통일성있게 create()를 사용하는게 더 좋으면 수정해서 올리겠슴다~!

2024-11-15 00:54 UTC, HoyeongJeon commented
> 말씀하시려는 의도가 현재 OAuth 로그인 과정처럼 런타임 시점에서 Clova, OpenAI를 지정해서 다형성을 통해 하나의 추상화된 인터페이스에 의존하도록 만들어 특정 구현체에 의존하지 않는게 좋겠다고 하시는 거라면 좋은 생각 같습니다! (사실 난 너무 좋아요.. 대단쓰)

맞습니다~! 

> 그런데 코드가 특정 기술에 종속적이면 안좋은걸까요? 클로바는 저희 서비스의 핵심 AI 서비스라 변경될 일이 없고 계속해서 사용될거라 생각하는데 서비스에서 명시적으로 `클로바 추천을 얻어오는 기능`을 담당하고 있는데 이거를 추상화해버리면 어디서 추천을 해오는지 쉽게 확인할 수 있을까요? 위 질문은 단순 저만의 고민입니다 ㅋㅋㅋ 종속을 피하고 추상화를 하는게 과연 옳을까? 라는 생각이 들었어서 저 자신에게 질문을 했던 거라 너무 깊게 고민 안하셔도 될 거 같아요!

아하 추천을 받아오는 controller이름이 일단 GetRecommendationFromClovaController이기도 하고 Message에서 분기 처리를 통해 Online, Offline의 추천 프롬프트를 구분했듯이 , 현재 Online, Offline 에 따라 추천을 받아오는 AI가 다르니까 괜히 컨틀롤러와 서비스를 두개를 만들기보다 하나로 추상화해서 사용하는게 더 낫지않을까? 생각했어요!! 

> 우선 추상화해서 작업을 하는건 너무 좋을 거 같은데 이번 스프린트도 얼마 남지 않았고(할 작업이 생각보다 많음..) 이 작업을 토대로 OpenAI도 변경해야해서 위 내용은 슬랙에 적어두고 추후 기능 구현 다하고 리팩토링하거나 중간에 시간 될 때 변경하면 좋을 거 같습니다!
> 
> 근데 이건 제 생각이라 호영이형의 생각을 말해주시면 그걸로 결정하면 될 거 같아요~

그럼 일단 구현 다 하구 나중에 리팩토링하는거로 하죠!!!

2024-11-15 16:14 UTC, anxi01 commented on src/main/java/spring/backend/recommendation/infrastructure/clova/application/ClovaRecommendationProvider.java
> +            WebClient webClient = WebClient.builder()
builder가 별로는 아닙니다
그런데 builder로 하시는 이유가 있어야 제 생각엔 좋은 코드라고 생각해요!
제가 생각한 builder와 create로 객체 생성의 차이는
- builder : 여러 옵션을 추가하여 생성함
- create : 단순하게 객체를 생성함
라고 생각하는데 지금 builder를 통해 header만 설정하고 있어서 create로 해도 되지 않을까 라는 이유였습니다

https://oliveyoung.tech/blog/2022-11-10/oliveyoung-discovery-premium-webclient/
올리브영에서 WebClient를 사용할 때 builder를 쓴 이유가 적혀있어 참고해보시면 좋을 거 같습니다
(꼭 수정할 필요는 없습니다~)

2024-11-15 16:18 UTC, anxi01 approved these changes
고생하셨습니다!
WebClient는 수정 필수는 아니라서 builder와 create의 차이 정도만 이해하고 넘어가셔도 좋을 거 같습니다

Controller는 추상화할지, 기능 별로 나눌지 (온, 오프, 온오프 모두) 같이 고민 해봐요!

2024-11-15 16:27 UTC, merged