Feat: (#78) 자투리 시간을 초과한 활동은 자동으로 종료처리한다
KUSITMS-30th-TEAM-C/backend pull request #93
Opened 2024-11-15 00:39 UTC by anxi01

## ✅ PR 유형
어떤 변경 사항이 있었나요?

- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [x] 빌드 부분 혹은 패키지 매니저 수정
- [x] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

---

## 📝 작업 내용
- RabbitMQ를 이용해 사용자의 자투리 시간이 지났을 때 메시지 큐를 이용해 비동기로 자동 종료하는 작업입니다.
- Delay Queue Plugin을 설치하여 자투리 시간 만큼 지연 시간을 두고 처리하게 하였습니다.
- application.yml에 RabbitMQ 및 큐 관련 설정 추가되었습니다.

### 성공 응답
![스크린샷 2024-11-15 오전 9 06 38](https://github.com/user-attachments/assets/4bce7f6b-0594-4bfe-b7a3-32032a83cc1c)
![스크린샷 2024-11-15 오전 9 07 00](https://github.com/user-attachments/assets/44371c72-8932-43e7-9918-87fe8084cad3)

### 성공 영상

https://github.com/user-attachments/assets/7a8302e1-d634-4ac2-a862-b5239405becf

---

## ✏️ 관련 이슈
- Resolves : #78 

---

## 🎸 기타 사항 or 추가 코멘트
- 'docker-compose.yml' 에서 docker-compose로 배포환경에 띄워야하는데 내가 함부로 수정하면 안될 거 같아서 docker-compose만 수정하고 이외 env, application.yml(서버 배포용)은 아직 수정하지 않았습니다.. 형이 인프라 신이니까 내가 수정해도 괜찮을지 확인해주면 좋을 거 같아용

2024-11-15 06:20 UTC, HoyeongJeon commented
일단 docker-compose 수정해도 괜찮아!!

2024-11-15 11:54 UTC, HoyeongJeon requested changes

2024-11-15 11:54 UTC, HoyeongJeon commented on docker-compose-local.yml
> +    image: heidiks/rabbitmq-delayed-message-exchange:latest
특별한 이유가 없다면 latest 버전보단 특정 버전을 명시하는게 좋다 생각합니다..!

2024-11-15 11:54 UTC, HoyeongJeon commented on docker-compose.yml
> +    image: heidiks/rabbitmq-delayed-message-exchange:latest
같은 이유!

2024-11-15 12:20 UTC, HoyeongJeon requested changes

2024-11-15 12:20 UTC, HoyeongJeon commented on src/main/java/spring/backend/core/infrastructure/queue/MessageProducer.java
> +    private static final RabbitTemplate rabbitTemplate = ApplicationContextProvider.getBean("rabbitTemplate", RabbitTemplate.class);
static 필드로 사용하는 것이 일반적인 방법인가요 ? 

```Java
private final RabbitTemplate rabbitTemplate; 
```

이렇게 인스턴스로 받는 것은 안되나요???

2024-11-15 12:23 UTC, HoyeongJeon requested changes

2024-11-15 12:23 UTC, HoyeongJeon commented on docker-compose-local.yml
> +
rabbitmq는 값을 저장하지 않나요??
영속성이 필요하면 rabbitmq 용 볼륨도 설정하면 좋을거같아요~!

2024-11-15 12:41 UTC, HoyeongJeon requested changes

2024-11-15 12:41 UTC, HoyeongJeon commented on src/main/java/spring/backend/core/infrastructure/queue/MessageProducer.java
> +    public void publishMessage() {
이건 메시지 발행 후 바로 처리되는 메서드인가요 ? 

`publishMessageWithDelay`는 지연시간을 걸어놓은 것이라면 
메시지를 즉시 처리하는 메서드는 왜 있는건가요??
지연시간이 흘렀을 때 자동 종료하는 용도라면 아래만 있어도 되는거 아닌가 싶어서요..

2024-11-15 12:46 UTC, HoyeongJeon commented
제가 못찾은거같은데 그 사용자가 종료버튼을 눌렀을 때 api는 아직 없는거죠?

2024-11-15 12:46 UTC, HoyeongJeon commented on src/main/java/spring/backend/core/infrastructure/queue/MessageProducer.java
> +    public void publishMessage() {
아직 사용자가 종료 버튼을 눌렀을 때를 처리하는 api는 없는거죠?

2024-11-15 12:47 UTC, HoyeongJeon commented
고생하셨습니다!!
메시지 큐 자체를 안써봐서 궁금한게 많았어요 ㅎㅎ
메시지 큐를 모르는 입장에서 코드가 어떻다 저렇다 하는 것은 말이 안되기에 , 나름 찾아보면서 궁금한 부분들을 리뷰로 달았습니다.

2024-11-15 17:12 UTC, anxi01 commented on src/main/java/spring/backend/core/infrastructure/queue/MessageProducer.java
> +    private static final RabbitTemplate rabbitTemplate = ApplicationContextProvider.getBean("rabbitTemplate", RabbitTemplate.class);
> static 필드로 사용하는 것이 일반적인 방법인가요 ?

정적 변수로 선언 vs 멤버 변수로 선언 -> 뭐가 더 일반적일까요??
저는 둘 다 일반적으로 사용된다고 생각합니다 (질문 의도에 대한 답이 맞는지 모르겠네요ㅜ)

2024-11-15 17:12 UTC, anxi01 commented on src/main/java/spring/backend/core/infrastructure/queue/MessageProducer.java
> +    private static final RabbitTemplate rabbitTemplate = ApplicationContextProvider.getBean("rabbitTemplate", RabbitTemplate.class);
> ```java
> private final RabbitTemplate rabbitTemplate; 
> ```
> 
> 이렇게 인스턴스로 받는 것은 안되나요???

그렇게 받아도 되지만 static으로 받은 이유는 다음과 같습니다.
- 하위 구현체에서 상속을 통해 Producer 인스턴스를 생성하는데 만약 정적변수로 사용하지 않는다면 Producer구현체를 생성할 때마다 RabbitTemplate를 생성자에 넣어줘야 합니다. 이럴 경우, 생성 시점에서 RabbitTemplate가 해당 클래스에 생성되어있어야하기 때문에 static으로 사용하였습니다. (RabbitTemplate가 생성 시점 사용되는 클래스에 종속)
- RabbitTemplate을 모든 인스턴스에서 공유해서 사용하기 위해 정적 변수로 사용했습니다.

예시) rabbitTemplte를 DI해서 사용할 경우
```java
@Service
@RequiredArgsConstructor
public class FinishActivityAutoService {

    private final FinishActivityQueueProperty finishActivityQueueProperty;
  
    // 외부 모듈을 DI하는 문제 발생
    private final RabbitTemplate rabbitTemplate;

    public void finishActivityAuto(Activity activity) {
        int spareTime = activity.getSpareTime();
        FinishActivityMessageProducer finishActivityMessageProducer = new FinishActivityMessageProducer(
                rabbitTemplate, // 변경된 코드
                finishActivityQueueProperty,
                FinishActivityMessage.builder()
                        .activityId(activity.getId())
                        .spareTime(spareTime)
                        .build()
        );
        long delayTime = (long) spareTime * 60 * 1000;
        finishActivityMessageProducer.publishMessageWithDelay(delayTime);
    }
}
```

2024-11-15 17:13 UTC, anxi01 commented on src/main/java/spring/backend/core/infrastructure/queue/MessageProducer.java
> +    public void publishMessage() {
> 아직 사용자가 종료 버튼을 눌렀을 때를 처리하는 api는 없는거죠?

```java
@RestController
@RequiredArgsConstructor
public class FinishActivityController implements FinishActivitySwagger {

    private final FinishActivityService finishActivityService;

    @Authorization
    @PatchMapping("/v1/activities/{activityId}/finish")
    public ResponseEntity<RestResponse<FinishActivityResponse>> finishActivity(@AuthorizedMember Member member, @PathVariable Long activityId) {
        return ResponseEntity.ok(new RestResponse<>(finishActivityService.finishActivity(member, activityId)));
    }
}
``` 
이미 구현되어 있습니당

2024-11-15 17:16 UTC, anxi01 commented on src/main/java/spring/backend/core/infrastructure/queue/MessageProducer.java
> +    public void publishMessage() {
> 이건 메시지 발행 후 바로 처리되는 메서드인가요 ?
> 
> `publishMessageWithDelay`는 지연시간을 걸어놓은 것이라면 메시지를 즉시 처리하는 메서드는 왜 있는건가요??
> 
> ㅇㅏ 사용자가 종료버튼을 눌렀을 때 메시지를 처리하기 위해 만든 메서드인건가요??

사용자가 종료버튼을 눌렀을 때 종료하는 API는 이미 구현되어있습니다.
`publishMessage` 메소드를 만든 건 보통 MQ는 메시지 발행을 딜레이시켜서 하지 않는다고 알고 있습니다
저희 기능의 경우 특수하기 때문에 딜레이시켜서 메시지를 큐에 보내는 거예요!

보통은 즉시 메시지를 발행하는 걸로 알고 있는데 추후 MQ를 사용할 때 딜레이시키지 않고 바로 메시지를 보내야할 수 있어서 확장성을 고려하여 미리 만들어두었습니다

2024-11-15 18:10 UTC, anxi01 commented on docker-compose-local.yml
> +    image: heidiks/rabbitmq-delayed-message-exchange:latest
조아요~

2024-11-15 18:11 UTC, anxi01 commented on docker-compose-local.yml
> +
어우 조아요~

2024-11-16 02:05 UTC, HoyeongJeon commented on src/main/java/spring/backend/core/infrastructure/queue/MessageProducer.java
> +    private static final RabbitTemplate rabbitTemplate = ApplicationContextProvider.getBean("rabbitTemplate", RabbitTemplate.class);
아하 이 부분에 대해서 물어봤던 것은 
getBean을 통해서 Spring 컨텍스트에 직접 접근하는 것이 올바른가? 란 생각에 질문했던 것입니다. 
ApplicationContextProvider를 사용해 직접 빈에 접근하는 것 (서비스 로케이터 패턴으로 보입니다..!) 서비스 로케이터 패턴이 DI 프레임워크에서 안티패턴이라 여겨지는 경우도 있다고 봐서요. 

https://www.rcook.net/Service-Locators-Anti-Pattern-or-Just-Misunderstood
https://deviq.com/antipatterns/service-locator

그런데 명확한 이유를 가지고 쓰면 별 상관없다 생각합니다..!

2024-11-16 02:11 UTC, HoyeongJeon requested changes

2024-11-16 02:11 UTC, HoyeongJeon commented on src/main/java/spring/backend/core/configuration/RabbitMQConfiguration.java
> +    @Resource
@Resource로 의존성을 받는 이유가 있나요?

2024-11-16 02:28 UTC, HoyeongJeon commented on src/main/java/spring/backend/activity/application/FinishActivityAutoService.java
> +        int spareTime = activity.getSpareTime();
추후에 spareTime의 타입도 Integer -> int로 수정할 생각인가요?

2024-11-16 05:28 UTC, anxi01 commented on src/main/java/spring/backend/core/configuration/RabbitMQConfiguration.java
> +    @Resource
제가 이전 RabbitMQ를 공부하면서 `@Resource` 를 사용하길래 동일하게 적용했던 거 같습니다
다시 찾아보니 @Resource도 결국 DI여서 생성자 주입으로 변경하였습니다!
잘 몰랐는데 고마워용

2024-11-16 05:35 UTC, anxi01 commented on src/main/java/spring/backend/activity/application/FinishActivityAutoService.java
> +        int spareTime = activity.getSpareTime();
이 부분은 저번에 준영님께서 피드백 주신 Wrapper와 Primitive에 관한 리팩토링 여부를 여쭤보시는 거 같은데
지금 작업에서 수정하면 연관된 모든 부분이 수정돼서 리팩토링 작업은 추후 개발 끝나고 해도 괜찮지 않을까 생각됩니다

2024-11-16 08:20 UTC, HoyeongJeon approved these changes
고생하셨숨니다

2024-11-18 08:29 UTC, merged