Feat: (#87) 월 간 활동 요약 헤딩을 구현한다.
KUSITMS-30th-TEAM-C/backend pull request #94
Opened 2024-11-15 08:39 UTC by HoyeongJeon

## ✅ PR 유형
어떤 변경 사항이 있었나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

---

## 📝 작업 내용
이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

- 월간 활동 요약 헤딩을 구현했습니다. 
<img width="1343" alt="image" src="https://github.com/user-attachments/assets/6ab2b544-14c2-45ef-a378-f5a3b74766c0">

---

## ✏️ 관련 이슈
본인이 작업한 내용이 어떤 Issue Number와 관련이 있는지만 작성해주세요

ex)
- Fixes : #00 (수정중인 이슈)
- Resolves : #100 (무슨 이슈를 해결했는지)
- Ref : #00 #01 (참고할 이슈)
- Related to : #00 #01 (해당 커밋과 관려)

---

## 🎸 기타 사항 or 추가 코멘트

2024-11-15 16:54 UTC, anxi01 requested changes
현재 작업에 대해서 프론트와 논의 후에 작업을 하셨을까요?

예를 들면,
- 트리맵 뷰에서 단순 활동 개수만 보내주면 자동으로 사이즈를 프론트에서 처리하는지
- `리스트는 ‘최초 가입 달 ~ 이번달(해당 달)’로 구성되며` 에서 최초 가입 달은 어떻게 처리할건지
- 키워드는 Enum으로 보내줄건지, 아님 Enum의 description으로 보내줄건지

등 상호 논의가 필요한 지점이 많다고 생각이 들어서요!

논의가 진행되어 작업을 하셨다면, 슬랙 쓰레드나 논의한 내용을 알려주시면 좋을 거 같습니다!
만약 논의가 진행되지 않았다면, 논의를 진행한 후에 작업을 하시는게 좋을 거 같습니다!

프론트와 논의하지 않고 작업을 해서 커밋을 남겼는데 이후 여러 부분이 바뀌게 되어 수정 커밋이 많아지면 나중에 이 프로젝트의 커밋을 볼 때 작업 내용보다 수정 커밋이 더 많아질 수 있습니다.
더불어 추가 공수도 많이 들어요.!

개발 구현을 빠르게 하는 것도 좋지만 기획, 프론트와 충분한 상의 후에 작업을 진행하는 것이 더 빠른 작업이 될 수 있을 거 같습니다~

고생하셨습니다!

2024-11-15 16:54 UTC, anxi01 commented on src/main/java/spring/backend/activity/util/MonthRangeUtil.java
> +public class MonthRangeUtil {
시간에 관한 거니까 TimeUtil에 넣으면 어떨까요?

2024-11-15 16:54 UTC, anxi01 commented on src/main/java/spring/backend/activity/util/MonthRangeUtil.java
> +    public MonthRangeUtil(YearMonth yearMonth) {
보통 유틸 클래스는 객체를 생성하지 않고 static method로 무상태성을 갖습니다
@Component로 외부 리소스나 빈을 의존해서 사용하지 않을 거면 static method로 만드는 게 좋을 거 같습니다.

2024-11-15 16:54 UTC, anxi01 commented on src/main/java/spring/backend/activity/util/MonthRangeUtil.java
> +    private final LocalDateTime end;
```java
private final LocalDateTime start;
private final LocalDateTime end;
```
유틸 클래스는 객체 생성을 하지 않으니 변수 선언도 제거되어야할 거 같습니다

2024-11-15 16:54 UTC, anxi01 commented on src/main/java/spring/backend/activity/presentation/ReadMonthlyActivityOverviewController.java
> +    @GetMapping("/v1/activity")
`/v1/activity`는 현재 기능과 거리가 있어 보입니다
엔드포인트를 좀 더 고민해보는게 좋을 거 같아요!

2024-11-15 16:54 UTC, anxi01 commented on src/main/java/spring/backend/activity/presentation/ReadMonthlyActivityOverviewController.java
> +            @Valid @ModelAttribute MonthlyActivityOverviewRequest monthlyActivityOverviewRequest
q) @ModelAttribute를 사용한 이유가 무엇인가요?

2024-11-15 16:54 UTC, anxi01 commented on src/main/java/spring/backend/activity/presentation/ReadMonthlyActivityOverviewController.java
> +    public ResponseEntity<RestResponse<MonthlyActivityOverviewResponse>> readMonthlyActivityOverviewController(
메소드명에 controller가 제거되는게 좋을 거 같습니다

2024-11-15 16:54 UTC, anxi01 commented on src/main/java/spring/backend/activity/dto/response/MonthlyActivityCountByKeywordResponse.java
> +        Long activityCount
![스크린샷 2024-11-16 오전 1 38 55](https://github.com/user-attachments/assets/baa3d1c5-5e91-4fc8-ac63-3e2dcf3f5fc2)

저번에 피드백 받은 내용인데,
Wrapper 타입보다 primitive 타입을 쓰는게 좋을 거 같아요!

2024-11-15 16:54 UTC, anxi01 commented on src/main/java/spring/backend/activity/dto/response/MonthlyActivityOverviewResponse.java
> +        MonthlySavedTimeAndActivityCountResponse monthlySavedTimeAndActivityCountResponse,
q) @JsonProperty를 사용한 이유가 있을까요?

`MonthlySavedTimeAndActivityCountResponse monthlySavedTimeAndActivityCount` 로 변수명을 지었다면 @JsonProperty가 필요하지 않을 것으로 보이긴 합니다..!

2024-11-15 16:56 UTC, anxi01 commented on src/main/java/spring/backend/activity/util/MonthRangeUtil.java
> +    public MonthRangeUtil(YearMonth yearMonth) {
유틸 클래스를 검색하면 잘 정리한 블로그가 많이 있어서 한 번 보시는 거 추천드려요!

2024-11-16 01:38 UTC, HoyeongJeon commented on src/main/java/spring/backend/activity/dto/response/MonthlyActivityOverviewResponse.java
> +        MonthlySavedTimeAndActivityCountResponse monthlySavedTimeAndActivityCountResponse,
반환값에 Response까지 붙여서 가는게 굳이 붙어있어 보여서 추가했습니다.

2024-11-16 01:40 UTC, HoyeongJeon commented
> * 트리맵 뷰에서 단순 활동 개수만 보내주면 자동으로 사이즈를 프론트에서 처리하는지
> * `리스트는 ‘최초 가입 달 ~ 이번달(해당 달)’로 구성되며` 에서 최초 가입 달은 어떻게 처리할건지
> * 키워드는 Enum으로 보내줄건지, 아님 Enum의 description으로 보내줄건지

논의없이 작업을 했네요
오늘 만나서 얘기를 나눠봐야겠습니다.

2024-11-16 01:46 UTC, HoyeongJeon commented on src/main/java/spring/backend/activity/presentation/ReadMonthlyActivityOverviewController.java
> +            @Valid @ModelAttribute MonthlyActivityOverviewRequest monthlyActivityOverviewRequest
@RequestParam 대신 @ModelAttribute를 사용한 이유를 묻는거라면 파라미터가 2개 이상이기에 간소화해서 받기위해 사용했습니다. 
또 유효성 검사를 할때에도 @ReqeustParam은 컨트롤러의 API 파라미터 옆에 붙이기에 @ModelAttribute안에 유효성 조건을 설정하고 @Valid로 받는 것이 더 깔끔해서 @ModelAttribute로 사용했습니다.

2024-11-16 01:47 UTC, HoyeongJeon commented on src/main/java/spring/backend/activity/util/MonthRangeUtil.java
> +    public MonthRangeUtil(YearMonth yearMonth) {
감사합니다~

2024-11-16 02:22 UTC, HoyeongJeon commented on src/main/java/spring/backend/activity/util/MonthRangeUtil.java
> +    public MonthRangeUtil(YearMonth yearMonth) {
파라미터로 YearMonth를 받아 기간을 설정해주는 코드인데, 찾아보니 유틸 클래스로 빼면 안될거같아요.
일단 start, end를 통해 상태를 유지해야 하기도 하니까 유틸로 고치기보단 converter로 빼는 것이 더 옳다 생각됩니다.
유틸 클래스가 아닌 Converter로 변경하겠습니다.

2024-11-16 02:30 UTC, HoyeongJeon commented on src/main/java/spring/backend/activity/dto/response/MonthlyActivityCountByKeywordResponse.java
> +        Long activityCount
좋아여

2024-11-16 06:13 UTC, anxi01 commented on src/main/java/spring/backend/activity/presentation/ReadMonthlyActivityOverviewController.java
> +            @Valid @ModelAttribute MonthlyActivityOverviewRequest monthlyActivityOverviewRequest
> 파라미터가 2개 이상이기에 간소화해서 받기위해 사용했습니다.

간소화한다는게 무슨 의미일까요?

```java
@Valid MonthlyActivityOverviewRequest monthlyActivityOverviewRequest
```
@ModelAttribute를 사용하지 않아도 동작하는 걸로 알고 있습니다 
(이전에 말했었던 GET 요청에서 `@RequestParam ` 를 붙이지 않아도 자동으로 쿼리스트링으로 붙여준다는 것을 의미합니다)

2024-11-18 07:54 UTC, anxi01 commented on src/main/java/spring/backend/activity/application/ReadMonthlyActivityOverviewService.java
> +        List<MonthlyActivityCountByKeywordResponse> activityByKeywordSummaryResponses = activityDao.findMonthlyActivitiesByKeywordSummary(member.getId(),TimeUtil.toStartDayOfMonth(yearMonth), TimeUti
```java
TimeUtil.toStartDayOfMonth(yearMonth), TimeUtil.toEndDayOfMonth(yearMonth)
```
이거 변수로 생성해서 넣어주는게 어떨까요??

2024-11-18 07:56 UTC, anxi01 commented on src/main/java/spring/backend/activity/application/ReadMonthlyActivityOverviewService.java
> +public class ReadMonthlyActivityOverviewService {
`도메인 주도 개발 시작하기` 에서 DAO를 이용하면 조회 응용서비스를 만들지 않고 
DAO -> Controller 로 응용계층 생략해도 괜찮다고 해서 Controller에서 처리해도 좋을 거 같아요~

<img width="413" alt="스크린샷 2024-10-02 오후 2 55 12" src="https://github.com/user-attachments/assets/643d028b-27e5-4b50-9608-8fc841509071">

2024-11-18 07:57 UTC, anxi01 commented on src/main/java/spring/backend/activity/dto/request/MonthlyActivityOverviewRequest.java
> +        @NotNull(message = "년도는 필수 입력 값입니다.")
primitive 타입이므로 `@NotNull` 은 사용하지 않아도 괜찮습니다!

2024-11-18 07:59 UTC, anxi01 commented on src/main/java/spring/backend/activity/dto/response/MonthlyActivityOverviewResponse.java
> +        Month joinedMonth,
q) 연도는 안보내줘도 괜찮나요?

2024-11-18 08:00 UTC, anxi01 commented on src/main/java/spring/backend/activity/dto/response/MonthlySavedTimeAndActivityCountResponse.java
> +        Long monthlyTotalSavedTime,
응답에서도 만약 값이 없으면 0으로 반환할 수 있게 primitive 타입으로 변경하는게 좋을 거 같습니다~

2024-11-18 08:04 UTC, anxi01 commented on src/main/java/spring/backend/activity/presentation/swagger/ReadMonthlyActivityOverviewSwagger.java
> +            operationId = "/v1/activity"
엔드포인트 수정해주세요~

2024-11-18 08:04 UTC, anxi01 commented on src/main/java/spring/backend/activity/presentation/swagger/ReadMonthlyActivityOverviewSwagger.java
> +@Tag(name = "Activity" , description = "활동")
의도하지 않은 공백이 있는 거 같아요!

2024-11-18 08:05 UTC, anxi01 commented on src/main/java/spring/backend/core/util/TimeUtil.java
> +    public static LocalDateTime toEndDayOfMonth(YearMonth yearMonth) {
유틸 클래스 👍

2024-11-19 04:48 UTC, HoyeongJeon commented on src/main/java/spring/backend/activity/application/ReadMonthlyActivityOverviewService.java
> +        List<MonthlyActivityCountByKeywordResponse> activityByKeywordSummaryResponses = activityDao.findMonthlyActivitiesByKeywordSummary(member.getId(),TimeUtil.toStartDayOfMonth(yearMonth), TimeUti
좋습니다~!

2024-11-19 05:06 UTC, HoyeongJeon commented on src/main/java/spring/backend/activity/application/ReadMonthlyActivityOverviewService.java
> +public class ReadMonthlyActivityOverviewService {
책의 해당 부분을 읽어봤는데, 
"서비스에서 수행하는 추가적인 로직이 없을뿐더러 단일 쿼리만 실행하는 조회 전용 기능..."
이 부분에서 조금 걸리는게 현재 우리 코드에선 날짜 변환 로직이 들어가있잖아요.

그래서 이걸 합치면, 표현계층에서 조회 + 날짜 변환도 함께 하게되니까 역할이 많아지는 것이 아닌가? 라는 고민이 있습니다..!

만약 날짜 변환코드도 조회에 다 합쳐버리면 
```Java
@RestController
@RequiredArgsConstructor
public class ReadMonthlyActivityOverviewController implements ReadMonthlyActivityOverviewSwagger {
    private final ReadMonthlyActivityOverviewService readMonthlyActivityOverviewService;
    private final ActivityDao activityDao;
    @Authorization
    @GetMapping("/v1/activities/overview")
    public ResponseEntity<RestResponse<MonthlyActivityOverviewResponse>> readMonthlyActivityOverview(
            @AuthorizedMember Member member,
            @Valid MonthlyActivityOverviewRequest monthlyActivityOverviewRequest
    ) {
        MonthlySavedTimeAndActivityCountResponse monthlySavedTimeAndActivityCountResponse = activityDao.findMonthlyTotalSavedTimeAndTotalCount(
                member.getId(),
                TimeUtil.toStartDayOfMonth(YearMonth.of(monthlyActivityOverviewRequest.year(), monthlyActivityOverviewRequest.month())),
                TimeUtil.toEndDayOfMonth(YearMonth.of(monthlyActivityOverviewRequest.year(), monthlyActivityOverviewRequest.month()))
        );
        List<MonthlyActivityCountByKeywordResponse> activityByKeywordSummaryResponses = activityDao.findMonthlyActivitiesByKeywordSummary(
                member.getId(),
                TimeUtil.toStartDayOfMonth(YearMonth.of(monthlyActivityOverviewRequest.year(), monthlyActivityOverviewRequest.month())),
                TimeUtil.toEndDayOfMonth(YearMonth.of(monthlyActivityOverviewRequest.year(),
                        monthlyActivityOverviewRequest.month()))
        );
        return ResponseEntity.ok(new RestResponse<>(new MonthlyActivityOverviewResponse(member.getUpdatedAt().getMonth(), monthlySavedTimeAndActivityCountResponse, activityByKeywordSummaryResponses)));
    }
}

```

이런식으로 해도 될거같긴한데, 무엇이 더 좋은 방향인지 모르겠어요.

2024-11-19 05:08 UTC, HoyeongJeon commented on src/main/java/spring/backend/activity/dto/response/MonthlyActivityOverviewResponse.java
> +        Month joinedMonth,
엇 제가 잘못생각했네요..!
수정할게요~!

2024-11-19 05:12 UTC, HoyeongJeon commented on src/main/java/spring/backend/activity/presentation/swagger/ReadMonthlyActivityOverviewSwagger.java
> +@Tag(name = "Activity" , description = "활동")
수정할게요~!

2024-11-19 09:11 UTC, anxi01 commented on src/main/java/spring/backend/activity/application/ReadMonthlyActivityOverviewService.java
> +public class ReadMonthlyActivityOverviewService {
저는 응용서비스로 뺀 지금처럼 해도 좋아요~! 
호영이형이 생각이 기우는 쪽으로 선택하면 될 거 같습니다!

2024-11-19 09:14 UTC, anxi01 commented on src/main/java/spring/backend/activity/application/ReadMonthlyActivityOverviewService.java
> +        return new MonthlyActivityOverviewResponse(member.getUpdatedAt().getYear() ,member.getUpdatedAt().getMonth(), monthlySavedTimeAndActivityCountResponse, activityByKeywordSummaryResponses);
```(member.getUpdatedAt().getYear() ,member.getUpdatedAt().getMonth(),```
여기 의도치 않은 공백..!

2024-11-19 11:48 UTC, HoyeongJeon commented on src/main/java/spring/backend/activity/application/ReadMonthlyActivityOverviewService.java
> +public class ReadMonthlyActivityOverviewService {
엇 그러면 이건 그냥 서비스로 둘게요 ㅎㅎ

2024-11-19 11:48 UTC, HoyeongJeon commented on src/main/java/spring/backend/activity/application/ReadMonthlyActivityOverviewService.java
> +        return new MonthlyActivityOverviewResponse(member.getUpdatedAt().getYear() ,member.getUpdatedAt().getMonth(), monthlySavedTimeAndActivityCountResponse, activityByKeywordSummaryResponses);
진짜 대박..! 매의눈

2024-11-19 18:50 UTC, anxi01 approved these changes
LGTM~!

2024-11-20 06:05 UTC, merged