Feat: (#95) 특정 달에 해당하는 키워드 별 활동 리스트 조회 API를 구현한다.
KUSITMS-30th-TEAM-C/backend pull request #97
Opened 2024-11-16 16:16 UTC by HoyeongJeon

## ✅ PR 유형
어떤 변경 사항이 있었나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

---

## 📝 작업 내용

- 특정 달에 해당하는 키워드 별 활동 리스트 조회 API를 구현했습니다.

**요청**

![image](https://github.com/user-attachments/assets/4f899f8c-fe27-498c-8f2a-51e9dda5f9a6)

**응답**
- 키워드에 대한 해당하는 활동이 있는 경우
![image](https://github.com/user-attachments/assets/8f488557-23c0-4be3-815f-f97f506ffca3)

- 키워드에 대한 활동이 없는 경우(기본적으로 활동이 없는 키워드는 선택할 수 없습니다.)
![image](https://github.com/user-attachments/assets/46e0210d-629d-40a8-9629-cd8b165ee114)

---

## ✏️ 관련 이슈
- Resolves : #95 
- Related to : #94 

---

## 🎸 기타 사항 or 추가 코멘트
- keyword category와 image를 매핑해서 Keyword로 반환하는 mapper를 구현했습니다. Domain에 넣기엔 Domain의 메인 로직이 아니고, 그저 변환만 수행하는 코드여서 infrastructure에 넣었습니다. 해당 코드를 dto에 넣을까 고민도 했지만, actvity 메서드 외에도 쓰이기에 activity/infrastructrue에 구현했습니다. 위치에 대한 고민이 있으니 의견주세요.
- #94 머지 후 머지될 예정입니다. 
- Wrapper 클래스를 지양하려 했지만, jpql의 sum은 null을 반환하기에 sum을 사용하는 dao는 반환타입으로 Long을 사용했습니다.

2024-11-20 09:47 UTC, anxi01 requested changes
거의 대부분 질문이긴 한데 keywordCategory 부분은 한 번 더 확인해봐야할 거 같습니다~
고생하셨습니당

2024-11-20 09:47 UTC, anxi01 commented on src/main/java/spring/backend/activity/application/ReadActivitiesByMemberAndKeywordInMonthService.java
> +        long totalSavedTimeByKeywordInMonth = activityDao.totalSavedTimeByKeywordInMonth(member.getId(), firstDayOfMonth, endDayOfMonth, keywordCategory);
q) 쿼리가 현재 3개씩 사용되는데 
```java
long countActivitiesByMemberAndKeywordInMonth = activityDao.countActivitiesByMemberAndKeywordInMonth(member.getId(), firstDayOfMonth, endDayOfMonth, keywordCategory);
long totalSavedTimeByKeywordInMonth = activityDao.totalSavedTimeByKeywordInMonth(member.getId(), firstDayOfMonth, endDayOfMonth, keywordCategory);
```
이거는 하나의 쿼리로 합칠 수 있지 않을까요?

2024-11-20 09:47 UTC, anxi01 commented on src/main/java/spring/backend/activity/dto/response/ActivitiesByMemberAndKeywordInMonthResponse.java
> +        Keyword keyword
example은 Keyword의 Category를 의미해서 자세하게 적어주세요~

2024-11-20 09:47 UTC, anxi01 commented on src/main/java/spring/backend/activity/application/ReadActivitiesByMemberAndKeywordInMonthService.java
> +        Keyword keyword = KeywordImageMapper.getImageByCategory(keywordCategory);
q) 프론트에서 Category를 가지고 이미지로 변환할 순 없을까요??

클로바 추천 API에서 Keyword대신 keywordCategory만 반환해서
저는 프론트에서 keywordCategory를 가지고 이미지를 매핑해서 사용하는줄 알았는데 아닐까요? 
어떻게 하기로 했는지 알려주세요~([문의 슬랙](https://meetup-c.slack.com/archives/C07N89FRW1M/p1732094744117539))

2024-11-20 09:47 UTC, anxi01 commented on src/main/java/spring/backend/activity/dto/response/ActivityWithTitleAndSavedTimeResponse.java
> +        LocalDateTime createdAt
JsonProperty보다 변수명을 dateOfActivity 로 하는게 명확할 거 같아요

2024-11-20 09:47 UTC, anxi01 commented on src/main/java/spring/backend/activity/presentation/ReadActivitiesByMemberAndKeywordInMonthController.java
> +@Validated
q) 아래 PathVariable에는 유효성 검사가 따로 없는데 사용하신 이유가 있을까요?

2024-11-20 09:47 UTC, anxi01 commented on src/main/java/spring/backend/activity/presentation/ReadActivitiesByMemberAndKeywordInMonthController.java
> +    @GetMapping("/v1/activities/{year}/{month}/keyword/{keywordCategory}")
q) 엔드포인트를 쿼리스트링이 아닌 PathVariable로 설정하신 이유가 있을까요?
그리고 year, month, keywordCategory의 순서는 어떤 의도로 배치하신걸까요?

2024-11-20 09:47 UTC, anxi01 commented on src/main/java/spring/backend/activity/application/ReadActivitiesByMemberAndKeywordInMonthService.java
> +        Keyword keyword = KeywordImageMapper.getImageByCategory(keywordCategory);
프론트에서는 keywordCategory 가지고 이미지 매핑해서 보여준다네요~
keywordCategory만 보내줘도 될 거 같아요!

2024-11-20 11:45 UTC, HoyeongJeon commented on src/main/java/spring/backend/activity/application/ReadActivitiesByMemberAndKeywordInMonthService.java
> +        long totalSavedTimeByKeywordInMonth = activityDao.totalSavedTimeByKeywordInMonth(member.getId(), firstDayOfMonth, endDayOfMonth, keywordCategory);
이걸 합칠 수 있는데, 
```
public record TotalSavedTimeAndActivityCountByKeywordInMonth(
        @Schema(description = "이번 달 해당 키워드 활동을 통해 모은 자투리 시간(분단위)", example = "120")
        long totalSavedTimeByKeywordInMonth,

        @Schema(description = "활동 키워드별 활동 총 개수")
        long totalActivityCountByKeywordInMonth
) {
}
```
Response dto를 만들어서 보내면 

![image](https://github.com/user-attachments/assets/3ed023e9-7478-4985-a391-b2fab19efa8b)

프론트에서 값을 얻을 때 한번 더 객체를 분해해야하니까 좀 불편하지 않을까 싶어서 두개로 나눴습니다.

아니면 totalSavedTimeAndActivityCountByKeywordInMonth.total~ 이렇게 값을 뽑아오는 방식을 써도 될거같긴한데 그러려면 원시형을 래퍼클래스로 바꿔야하니까 굳이아닐까? 생각했는데요, 어떤부분이 더 좋은지 모르겠네요..
의견주세요!

2024-11-20 11:45 UTC, HoyeongJeon commented on src/main/java/spring/backend/activity/dto/response/ActivitiesByMemberAndKeywordInMonthResponse.java
> +        Keyword keyword
네~

2024-11-20 11:55 UTC, HoyeongJeon commented on src/main/java/spring/backend/activity/presentation/ReadActivitiesByMemberAndKeywordInMonthController.java
> +    @GetMapping("/v1/activities/{year}/{month}/keyword/{keywordCategory}")
오버뷰의 엔드포인트가 ?year={year}&month={month} 라서 순서를 year, month, keyword로 배치했습니다.
PathVariable로 했던 건 이전에 엔드포인트를 activities로 시작을 통일하려헀어서 queryString으로 하면 같은 쿼리스트링 시작이 2개니까 에러가 터져서 PathVariable로 했던건데, 엔드포인트 시작을 바꾸면 될거같아요

2024-11-20 12:04 UTC, anxi01 commented on src/main/java/spring/backend/activity/application/ReadActivitiesByMemberAndKeywordInMonthService.java
> +        long totalSavedTimeByKeywordInMonth = activityDao.totalSavedTimeByKeywordInMonth(member.getId(), firstDayOfMonth, endDayOfMonth, keywordCategory);
DAO를 쿼리 조회만으로 사용하는 이유가 제 생각은 최소한의 쿼리로 다 가져올 수 있어서라고 생각을 했어요! (+ 메소드 명이 JPA 쿼리메소드에 비해 직관적이기도,,)

그래서 저는 쿼리가 2개보다는 1개로 줄일 수 있다면 줄이는 게 좋을 거 같아요~
>

2024-11-20 14:20 UTC, HoyeongJeon commented on src/main/java/spring/backend/activity/presentation/ReadActivitiesByMemberAndKeywordInMonthController.java
> +@Validated
PostMan으로 할 때 에러가 발생해서 되는줄 알았어요..!

2024-11-20 14:23 UTC, HoyeongJeon commented on src/main/java/spring/backend/activity/application/ReadActivitiesByMemberAndKeywordInMonthService.java
> +        long totalSavedTimeByKeywordInMonth = activityDao.totalSavedTimeByKeywordInMonth(member.getId(), firstDayOfMonth, endDayOfMonth, keywordCategory);
엇 제가 코드를 잘못짜서 에러가 발생했었던거 같아요

2024-11-20 15:11 UTC, anxi01 commented on src/main/java/spring/backend/activity/infrastructure/mapper/KeywordImageMapper.java
> +public class KeywordImageMapper {
q) 이거 제거해도 되지 않나요??

2024-11-20 15:12 UTC, anxi01 commented on src/main/java/spring/backend/activity/presentation/ReadActivitiesByMemberAndKeywordInMonthController.java
> +    @GetMapping("/v1/activities")
엔드포인트를 지금 기능에 맞게 수정하면 좋을 거 같아요!

2024-11-21 06:09 UTC, HoyeongJeon commented on src/main/java/spring/backend/activity/infrastructure/mapper/KeywordImageMapper.java
> +public class KeywordImageMapper {
프론트와 다시 논의한 결과 Keyword를 보내줄 때 이미지 주소도 함께 보내주는 것이 더 편하다고 해서 유지하는 것이 좋아보여요

2024-11-21 07:04 UTC, anxi01 commented on src/main/java/spring/backend/activity/infrastructure/mapper/KeywordImageMapper.java
> +public class KeywordImageMapper {
Mapper를 사용하지 않고, `Keyword`의 Category에서 private static으로 넣어도 괜찮을 거 같아요!
외부 모듈이 아니라 인프라에 위치하는 것보다 도메인에 있는게 좋을 듯!

2024-11-21 08:21 UTC, anxi01 approved these changes
고생하셨습니다!

2024-11-21 09:09 UTC, merged